#pragma once

#include <map>
#include <d3d12.h>
#include <set>
#include <Audio.h>

static inline std::unordered_map<D3D12_DESCRIPTOR_HEAP_TYPE, std::string> D3D12_DESCRIPTOR_HEAP_TYPEToString = {
	{ D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV, "CBV_SRV_UAV"},
	{ D3D12_DESCRIPTOR_HEAP_TYPE_SAMPLER, "SAMPLER"},
	{ D3D12_DESCRIPTOR_HEAP_TYPE_RTV, "RTV"},
	{ D3D12_DESCRIPTOR_HEAP_TYPE_DSV, "DSV"},
	{ D3D12_DESCRIPTOR_HEAP_TYPE_NUM_TYPES, "NUM_TYPES"},
};

static inline std::unordered_map<std::string, D3D12_DESCRIPTOR_HEAP_TYPE> StringToD3D12_DESCRIPTOR_HEAP_TYPE = {
	{ "CBV_SRV_UAV", D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV },
	{ "SAMPLER", D3D12_DESCRIPTOR_HEAP_TYPE_SAMPLER },
	{ "RTV", D3D12_DESCRIPTOR_HEAP_TYPE_RTV },
	{ "DSV", D3D12_DESCRIPTOR_HEAP_TYPE_DSV },
	{ "NUM_TYPES", D3D12_DESCRIPTOR_HEAP_TYPE_NUM_TYPES },
};

static inline std::unordered_map<DXGI_FORMAT, std::string> DXGI_FORMATToString = {
	{ DXGI_FORMAT_UNKNOWN, "UNKNOWN" },
	{ DXGI_FORMAT_R32G32B32A32_TYPELESS, "R32G32B32A32_TYPELESS" },
	{ DXGI_FORMAT_R32G32B32A32_FLOAT, "R32G32B32A32_FLOAT" },
	{ DXGI_FORMAT_R32G32B32A32_UINT, "R32G32B32A32_UINT" },
	{ DXGI_FORMAT_R32G32B32A32_SINT, "R32G32B32A32_SINT" },
	{ DXGI_FORMAT_R32G32B32_TYPELESS, "R32G32B32_TYPELESS" },
	{ DXGI_FORMAT_R32G32B32_FLOAT, "R32G32B32_FLOAT" },
	{ DXGI_FORMAT_R32G32B32_UINT, "R32G32B32_UINT" },
	{ DXGI_FORMAT_R32G32B32_SINT, "R32G32B32_SINT" },
	{ DXGI_FORMAT_R16G16B16A16_TYPELESS, "R16G16B16A16_TYPELESS" },
	{ DXGI_FORMAT_R16G16B16A16_FLOAT, "R16G16B16A16_FLOAT" },
	{ DXGI_FORMAT_R16G16B16A16_UNORM, "R16G16B16A16_UNORM" },
	{ DXGI_FORMAT_R16G16B16A16_UINT, "R16G16B16A16_UINT" },
	{ DXGI_FORMAT_R16G16B16A16_SNORM, "R16G16B16A16_SNORM" },
	{ DXGI_FORMAT_R16G16B16A16_SINT, "R16G16B16A16_SINT" },
	{ DXGI_FORMAT_R32G32_TYPELESS, "R32G32_TYPELESS" },
	{ DXGI_FORMAT_R32G32_FLOAT, "R32G32_FLOAT" },
	{ DXGI_FORMAT_R32G32_UINT, "R32G32_UINT" },
	{ DXGI_FORMAT_R32G32_SINT, "R32G32_SINT" },
	{ DXGI_FORMAT_R32G8X24_TYPELESS, "R32G8X24_TYPELESS" },
	{ DXGI_FORMAT_D32_FLOAT_S8X24_UINT, "D32_FLOAT_S8X24_UINT" },
	{ DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS, "R32_FLOAT_X8X24_TYPELESS" },
	{ DXGI_FORMAT_X32_TYPELESS_G8X24_UINT, "X32_TYPELESS_G8X24_UINT" },
	{ DXGI_FORMAT_R10G10B10A2_TYPELESS, "R10G10B10A2_TYPELESS" },
	{ DXGI_FORMAT_R10G10B10A2_UNORM, "R10G10B10A2_UNORM" },
	{ DXGI_FORMAT_R10G10B10A2_UINT, "R10G10B10A2_UINT" },
	{ DXGI_FORMAT_R11G11B10_FLOAT, "R11G11B10_FLOAT" },
	{ DXGI_FORMAT_R8G8B8A8_TYPELESS, "R8G8B8A8_TYPELESS" },
	{ DXGI_FORMAT_R8G8B8A8_UNORM, "R8G8B8A8_UNORM" },
	{ DXGI_FORMAT_R8G8B8A8_UNORM_SRGB, "R8G8B8A8_UNORM_SRGB" },
	{ DXGI_FORMAT_R8G8B8A8_UINT, "R8G8B8A8_UINT" },
	{ DXGI_FORMAT_R8G8B8A8_SNORM, "R8G8B8A8_SNORM" },
	{ DXGI_FORMAT_R8G8B8A8_SINT, "R8G8B8A8_SINT" },
	{ DXGI_FORMAT_R16G16_TYPELESS, "R16G16_TYPELESS" },
	{ DXGI_FORMAT_R16G16_FLOAT, "R16G16_FLOAT" },
	{ DXGI_FORMAT_R16G16_UNORM, "R16G16_UNORM" },
	{ DXGI_FORMAT_R16G16_UINT, "R16G16_UINT" },
	{ DXGI_FORMAT_R16G16_SNORM, "R16G16_SNORM" },
	{ DXGI_FORMAT_R16G16_SINT, "R16G16_SINT" },
	{ DXGI_FORMAT_R32_TYPELESS, "R32_TYPELESS" },
	{ DXGI_FORMAT_D32_FLOAT, "D32_FLOAT" },
	{ DXGI_FORMAT_R32_FLOAT, "R32_FLOAT" },
	{ DXGI_FORMAT_R32_UINT, "R32_UINT" },
	{ DXGI_FORMAT_R32_SINT, "R32_SINT" },
	{ DXGI_FORMAT_R24G8_TYPELESS, "R24G8_TYPELESS" },
	{ DXGI_FORMAT_D24_UNORM_S8_UINT, "D24_UNORM_S8_UINT" },
	{ DXGI_FORMAT_R24_UNORM_X8_TYPELESS, "R24_UNORM_X8_TYPELESS" },
	{ DXGI_FORMAT_X24_TYPELESS_G8_UINT, "X24_TYPELESS_G8_UINT" },
	{ DXGI_FORMAT_R8G8_TYPELESS, "R8G8_TYPELESS" },
	{ DXGI_FORMAT_R8G8_UNORM, "R8G8_UNORM" },
	{ DXGI_FORMAT_R8G8_UINT, "R8G8_UINT" },
	{ DXGI_FORMAT_R8G8_SNORM, "R8G8_SNORM" },
	{ DXGI_FORMAT_R8G8_SINT, "R8G8_SINT" },
	{ DXGI_FORMAT_R16_TYPELESS, "R16_TYPELESS" },
	{ DXGI_FORMAT_R16_FLOAT, "R16_FLOAT" },
	{ DXGI_FORMAT_D16_UNORM, "D16_UNORM" },
	{ DXGI_FORMAT_R16_UNORM, "R16_UNORM" },
	{ DXGI_FORMAT_R16_UINT, "R16_UINT" },
	{ DXGI_FORMAT_R16_SNORM, "R16_SNORM" },
	{ DXGI_FORMAT_R16_SINT, "R16_SINT" },
	{ DXGI_FORMAT_R8_TYPELESS, "R8_TYPELESS" },
	{ DXGI_FORMAT_R8_UNORM, "R8_UNORM" },
	{ DXGI_FORMAT_R8_UINT, "R8_UINT" },
	{ DXGI_FORMAT_R8_SNORM, "R8_SNORM" },
	{ DXGI_FORMAT_R8_SINT, "R8_SINT" },
	{ DXGI_FORMAT_A8_UNORM, "A8_UNORM" },
	{ DXGI_FORMAT_R1_UNORM, "R1_UNORM" },
	{ DXGI_FORMAT_R9G9B9E5_SHAREDEXP, "R9G9B9E5_SHAREDEXP" },
	{ DXGI_FORMAT_R8G8_B8G8_UNORM, "R8G8_B8G8_UNORM" },
	{ DXGI_FORMAT_G8R8_G8B8_UNORM, "G8R8_G8B8_UNORM" },
	{ DXGI_FORMAT_BC1_TYPELESS, "BC1_TYPELESS" },
	{ DXGI_FORMAT_BC1_UNORM, "BC1_UNORM" },
	{ DXGI_FORMAT_BC1_UNORM_SRGB, "BC1_UNORM_SRGB" },
	{ DXGI_FORMAT_BC2_TYPELESS, "BC2_TYPELESS" },
	{ DXGI_FORMAT_BC2_UNORM, "BC2_UNORM" },
	{ DXGI_FORMAT_BC2_UNORM_SRGB, "BC2_UNORM_SRGB" },
	{ DXGI_FORMAT_BC3_TYPELESS, "BC3_TYPELESS" },
	{ DXGI_FORMAT_BC3_UNORM, "BC3_UNORM" },
	{ DXGI_FORMAT_BC3_UNORM_SRGB, "BC3_UNORM_SRGB" },
	{ DXGI_FORMAT_BC4_TYPELESS, "BC4_TYPELESS" },
	{ DXGI_FORMAT_BC4_UNORM, "BC4_UNORM" },
	{ DXGI_FORMAT_BC4_SNORM, "BC4_SNORM" },
	{ DXGI_FORMAT_BC5_TYPELESS, "BC5_TYPELESS" },
	{ DXGI_FORMAT_BC5_UNORM, "BC5_UNORM" },
	{ DXGI_FORMAT_BC5_SNORM, "BC5_SNORM" },
	{ DXGI_FORMAT_B5G6R5_UNORM, "B5G6R5_UNORM" },
	{ DXGI_FORMAT_B5G5R5A1_UNORM, "B5G5R5A1_UNORM" },
	{ DXGI_FORMAT_B8G8R8A8_UNORM, "B8G8R8A8_UNORM" },
	{ DXGI_FORMAT_B8G8R8X8_UNORM, "B8G8R8X8_UNORM" },
	{ DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM, "R10G10B10_XR_BIAS_A2_UNORM" },
	{ DXGI_FORMAT_B8G8R8A8_TYPELESS, "B8G8R8A8_TYPELESS" },
	{ DXGI_FORMAT_B8G8R8A8_UNORM_SRGB, "B8G8R8A8_UNORM_SRGB" },
	{ DXGI_FORMAT_B8G8R8X8_TYPELESS, "B8G8R8X8_TYPELESS" },
	{ DXGI_FORMAT_B8G8R8X8_UNORM_SRGB, "B8G8R8X8_UNORM_SRGB" },
	{ DXGI_FORMAT_BC6H_TYPELESS, "BC6H_TYPELESS" },
	{ DXGI_FORMAT_BC6H_UF16, "BC6H_UF16" },
	{ DXGI_FORMAT_BC6H_SF16, "BC6H_SF16" },
	{ DXGI_FORMAT_BC7_TYPELESS, "BC7_TYPELESS" },
	{ DXGI_FORMAT_BC7_UNORM, "BC7_UNORM" },
	{ DXGI_FORMAT_BC7_UNORM_SRGB, "BC7_UNORM_SRGB" },
	{ DXGI_FORMAT_AYUV, "AYUV" },
	{ DXGI_FORMAT_Y410, "Y410" },
	{ DXGI_FORMAT_Y416, "Y416" },
	{ DXGI_FORMAT_NV12, "NV12" },
	{ DXGI_FORMAT_P010, "P010" },
	{ DXGI_FORMAT_P016, "P016" },
	{ DXGI_FORMAT_420_OPAQUE, "420_OPAQUE" },
	{ DXGI_FORMAT_YUY2, "YUY2" },
	{ DXGI_FORMAT_Y210, "Y210" },
	{ DXGI_FORMAT_Y216, "Y216" },
	{ DXGI_FORMAT_NV11, "NV11" },
	{ DXGI_FORMAT_AI44, "AI44" },
	{ DXGI_FORMAT_IA44, "IA44" },
	{ DXGI_FORMAT_P8, "P8" },
	{ DXGI_FORMAT_A8P8, "A8P8" },
	{ DXGI_FORMAT_B4G4R4A4_UNORM, "B4G4R4A4_UNORM" },
	{ DXGI_FORMAT_P208, "P208" },
	{ DXGI_FORMAT_V208, "V208" },
	{ DXGI_FORMAT_V408, "V408" },
	{ DXGI_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE,  "SAMPLER_FEEDBACK_MIN_MIP_OPAQUE" },
	{ DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE, "SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE" },
	{ DXGI_FORMAT_A4B4G4R4_UNORM, "A4B4G4R4_UNORM" },
	{ DXGI_FORMAT_FORCE_UINT, "FORCE_UINT" }
};

static inline std::unordered_map<std::string, DXGI_FORMAT> StringToDXGI_FORMAT = {
	{ "UNKNOWN", DXGI_FORMAT_UNKNOWN },
	{ "R32G32B32A32_TYPELESS", DXGI_FORMAT_R32G32B32A32_TYPELESS },
	{ "R32G32B32A32_FLOAT", DXGI_FORMAT_R32G32B32A32_FLOAT },
	{ "R32G32B32A32_UINT", DXGI_FORMAT_R32G32B32A32_UINT },
	{ "R32G32B32A32_SINT", DXGI_FORMAT_R32G32B32A32_SINT },
	{ "R32G32B32_TYPELESS", DXGI_FORMAT_R32G32B32_TYPELESS },
	{ "R32G32B32_FLOAT", DXGI_FORMAT_R32G32B32_FLOAT },
	{ "R32G32B32_UINT", DXGI_FORMAT_R32G32B32_UINT },
	{ "R32G32B32_SINT", DXGI_FORMAT_R32G32B32_SINT },
	{ "R16G16B16A16_TYPELESS", DXGI_FORMAT_R16G16B16A16_TYPELESS },
	{ "R16G16B16A16_FLOAT", DXGI_FORMAT_R16G16B16A16_FLOAT },
	{ "R16G16B16A16_UNORM", DXGI_FORMAT_R16G16B16A16_UNORM },
	{ "R16G16B16A16_UINT", DXGI_FORMAT_R16G16B16A16_UINT },
	{ "R16G16B16A16_SNORM", DXGI_FORMAT_R16G16B16A16_SNORM },
	{ "R16G16B16A16_SINT", DXGI_FORMAT_R16G16B16A16_SINT },
	{ "R32G32_TYPELESS", DXGI_FORMAT_R32G32_TYPELESS },
	{ "R32G32_FLOAT", DXGI_FORMAT_R32G32_FLOAT },
	{ "R32G32_UINT", DXGI_FORMAT_R32G32_UINT },
	{ "R32G32_SINT", DXGI_FORMAT_R32G32_SINT },
	{ "R32G8X24_TYPELESS", DXGI_FORMAT_R32G8X24_TYPELESS },
	{ "D32_FLOAT_S8X24_UINT", DXGI_FORMAT_D32_FLOAT_S8X24_UINT },
	{ "R32_FLOAT_X8X24_TYPELESS", DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS },
	{ "X32_TYPELESS_G8X24_UINT", DXGI_FORMAT_X32_TYPELESS_G8X24_UINT },
	{ "R10G10B10A2_TYPELESS", DXGI_FORMAT_R10G10B10A2_TYPELESS },
	{ "R10G10B10A2_UNORM", DXGI_FORMAT_R10G10B10A2_UNORM },
	{ "R10G10B10A2_UINT", DXGI_FORMAT_R10G10B10A2_UINT },
	{ "R11G11B10_FLOAT", DXGI_FORMAT_R11G11B10_FLOAT },
	{ "R8G8B8A8_TYPELESS", DXGI_FORMAT_R8G8B8A8_TYPELESS },
	{ "R8G8B8A8_UNORM", DXGI_FORMAT_R8G8B8A8_UNORM },
	{ "R8G8B8A8_UNORM_SRGB", DXGI_FORMAT_R8G8B8A8_UNORM_SRGB },
	{ "R8G8B8A8_UINT", DXGI_FORMAT_R8G8B8A8_UINT },
	{ "R8G8B8A8_SNORM", DXGI_FORMAT_R8G8B8A8_SNORM },
	{ "R8G8B8A8_SINT", DXGI_FORMAT_R8G8B8A8_SINT },
	{ "R16G16_TYPELESS", DXGI_FORMAT_R16G16_TYPELESS },
	{ "R16G16_FLOAT", DXGI_FORMAT_R16G16_FLOAT },
	{ "R16G16_UNORM", DXGI_FORMAT_R16G16_UNORM },
	{ "R16G16_UINT", DXGI_FORMAT_R16G16_UINT },
	{ "R16G16_SNORM", DXGI_FORMAT_R16G16_SNORM },
	{ "R16G16_SINT", DXGI_FORMAT_R16G16_SINT },
	{ "R32_TYPELESS", DXGI_FORMAT_R32_TYPELESS },
	{ "D32_FLOAT", DXGI_FORMAT_D32_FLOAT },
	{ "R32_FLOAT", DXGI_FORMAT_R32_FLOAT },
	{ "R32_UINT", DXGI_FORMAT_R32_UINT },
	{ "R32_SINT", DXGI_FORMAT_R32_SINT },
	{ "R24G8_TYPELESS", DXGI_FORMAT_R24G8_TYPELESS },
	{ "D24_UNORM_S8_UINT", DXGI_FORMAT_D24_UNORM_S8_UINT },
	{ "R24_UNORM_X8_TYPELESS", DXGI_FORMAT_R24_UNORM_X8_TYPELESS },
	{ "X24_TYPELESS_G8_UINT", DXGI_FORMAT_X24_TYPELESS_G8_UINT },
	{ "R8G8_TYPELESS", DXGI_FORMAT_R8G8_TYPELESS },
	{ "R8G8_UNORM", DXGI_FORMAT_R8G8_UNORM },
	{ "R8G8_UINT", DXGI_FORMAT_R8G8_UINT },
	{ "R8G8_SNORM", DXGI_FORMAT_R8G8_SNORM },
	{ "R8G8_SINT", DXGI_FORMAT_R8G8_SINT },
	{ "R16_TYPELESS", DXGI_FORMAT_R16_TYPELESS },
	{ "R16_FLOAT", DXGI_FORMAT_R16_FLOAT },
	{ "D16_UNORM", DXGI_FORMAT_D16_UNORM },
	{ "R16_UNORM", DXGI_FORMAT_R16_UNORM },
	{ "R16_UINT", DXGI_FORMAT_R16_UINT },
	{ "R16_SNORM", DXGI_FORMAT_R16_SNORM },
	{ "R16_SINT", DXGI_FORMAT_R16_SINT },
	{ "R8_TYPELESS", DXGI_FORMAT_R8_TYPELESS },
	{ "R8_UNORM", DXGI_FORMAT_R8_UNORM },
	{ "R8_UINT", DXGI_FORMAT_R8_UINT },
	{ "R8_SNORM", DXGI_FORMAT_R8_SNORM },
	{ "R8_SINT", DXGI_FORMAT_R8_SINT },
	{ "A8_UNORM", DXGI_FORMAT_A8_UNORM },
	{ "R1_UNORM", DXGI_FORMAT_R1_UNORM },
	{ "R9G9B9E5_SHAREDEXP", DXGI_FORMAT_R9G9B9E5_SHAREDEXP },
	{ "R8G8_B8G8_UNORM", DXGI_FORMAT_R8G8_B8G8_UNORM },
	{ "G8R8_G8B8_UNORM", DXGI_FORMAT_G8R8_G8B8_UNORM },
	{ "BC1_TYPELESS", DXGI_FORMAT_BC1_TYPELESS },
	{ "BC1_UNORM", DXGI_FORMAT_BC1_UNORM },
	{ "BC1_UNORM_SRGB", DXGI_FORMAT_BC1_UNORM_SRGB },
	{ "BC2_TYPELESS", DXGI_FORMAT_BC2_TYPELESS },
	{ "BC2_UNORM", DXGI_FORMAT_BC2_UNORM },
	{ "BC2_UNORM_SRGB", DXGI_FORMAT_BC2_UNORM_SRGB },
	{ "BC3_TYPELESS", DXGI_FORMAT_BC3_TYPELESS },
	{ "BC3_UNORM", DXGI_FORMAT_BC3_UNORM },
	{ "BC3_UNORM_SRGB", DXGI_FORMAT_BC3_UNORM_SRGB },
	{ "BC4_TYPELESS", DXGI_FORMAT_BC4_TYPELESS },
	{ "BC4_UNORM", DXGI_FORMAT_BC4_UNORM },
	{ "BC4_SNORM", DXGI_FORMAT_BC4_SNORM },
	{ "BC5_TYPELESS", DXGI_FORMAT_BC5_TYPELESS },
	{ "BC5_UNORM", DXGI_FORMAT_BC5_UNORM },
	{ "BC5_SNORM", DXGI_FORMAT_BC5_SNORM },
	{ "B5G6R5_UNORM", DXGI_FORMAT_B5G6R5_UNORM },
	{ "B5G5R5A1_UNORM", DXGI_FORMAT_B5G5R5A1_UNORM },
	{ "B8G8R8A8_UNORM", DXGI_FORMAT_B8G8R8A8_UNORM },
	{ "B8G8R8X8_UNORM", DXGI_FORMAT_B8G8R8X8_UNORM },
	{ "R10G10B10_XR_BIAS_A2_UNORM", DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM },
	{ "B8G8R8A8_TYPELESS", DXGI_FORMAT_B8G8R8A8_TYPELESS },
	{ "B8G8R8A8_UNORM_SRGB", DXGI_FORMAT_B8G8R8A8_UNORM_SRGB },
	{ "B8G8R8X8_TYPELESS", DXGI_FORMAT_B8G8R8X8_TYPELESS },
	{ "B8G8R8X8_UNORM_SRGB", DXGI_FORMAT_B8G8R8X8_UNORM_SRGB },
	{ "BC6H_TYPELESS", DXGI_FORMAT_BC6H_TYPELESS },
	{ "BC6H_UF16", DXGI_FORMAT_BC6H_UF16 },
	{ "BC6H_SF16", DXGI_FORMAT_BC6H_SF16 },
	{ "BC7_TYPELESS", DXGI_FORMAT_BC7_TYPELESS },
	{ "BC7_UNORM", DXGI_FORMAT_BC7_UNORM },
	{ "BC7_UNORM_SRGB", DXGI_FORMAT_BC7_UNORM_SRGB },
	{ "AYUV", DXGI_FORMAT_AYUV },
	{ "Y410", DXGI_FORMAT_Y410 },
	{ "Y416", DXGI_FORMAT_Y416 },
	{ "NV12", DXGI_FORMAT_NV12 },
	{ "P010", DXGI_FORMAT_P010 },
	{ "P016", DXGI_FORMAT_P016 },
	{ "420_OPAQUE", DXGI_FORMAT_420_OPAQUE },
	{ "YUY2", DXGI_FORMAT_YUY2 },
	{ "Y210", DXGI_FORMAT_Y210 },
	{ "Y216", DXGI_FORMAT_Y216 },
	{ "NV11", DXGI_FORMAT_NV11 },
	{ "AI44", DXGI_FORMAT_AI44 },
	{ "IA44", DXGI_FORMAT_IA44 },
	{ "P8", DXGI_FORMAT_P8 },
	{ "A8P8", DXGI_FORMAT_A8P8 },
	{ "B4G4R4A4_UNORM", DXGI_FORMAT_B4G4R4A4_UNORM },
	{ "P208", DXGI_FORMAT_P208 },
	{ "V208", DXGI_FORMAT_V208 },
	{ "V408", DXGI_FORMAT_V408 },
	{ "SAMPLER_FEEDBACK_MIN_MIP_OPAQUE", DXGI_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE },
	{ "SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE", DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE },
	{ "A4B4G4R4_UNORM", DXGI_FORMAT_A4B4G4R4_UNORM },
	{ "FORCE_UINT", DXGI_FORMAT_FORCE_UINT }
};

static inline std::unordered_map<DXGI_FORMAT, std::string> DXGI_DEPTH_FORMATToString =
{
	{ DXGI_FORMAT_D32_FLOAT, "D32_FLOAT" },
	{ DXGI_FORMAT_D24_UNORM_S8_UINT, "D24_UNORM_S8_UINT" }
};

static inline std::unordered_map<std::string, DXGI_FORMAT> StringTo_DXGI_DEPTH_FORMAT =
{
	{ "D32_FLOAT", DXGI_FORMAT_D32_FLOAT },
	{ "D24_UNORM_S8_UINT", DXGI_FORMAT_D24_UNORM_S8_UINT }
};

inline std::string FromDXGIFormat(DXGI_FORMAT v) { return DXGI_FORMATToString.at(v); }

inline DXGI_FORMAT ToDXGIFormat(std::string v) { return StringToDXGI_FORMAT.at(v); }

static inline std::set<DXGI_FORMAT> NonLinearDxgiFormats =
{
	DXGI_FORMAT_R8G8B8A8_UNORM_SRGB,
	DXGI_FORMAT_BC1_UNORM_SRGB,
	DXGI_FORMAT_BC2_UNORM_SRGB,
	DXGI_FORMAT_BC3_UNORM_SRGB,
	DXGI_FORMAT_B8G8R8A8_UNORM_SRGB,
	DXGI_FORMAT_B8G8R8X8_UNORM_SRGB,
	DXGI_FORMAT_BC7_UNORM_SRGB,
};

static inline std::unordered_map<D3D12_FILTER, std::string> D3D12_FILTERToString = {
	{ D3D12_FILTER_MIN_MAG_MIP_POINT, "MIN_MAG_MIP_POINT" },
	{ D3D12_FILTER_MIN_MAG_POINT_MIP_LINEAR, "MIN_MAG_POINT_MIP_LINEAR" },
	{ D3D12_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT, "MIN_POINT_MAG_LINEAR_MIP_POINT" },
	{ D3D12_FILTER_MIN_POINT_MAG_MIP_LINEAR, "MIN_POINT_MAG_MIP_LINEAR" },
	{ D3D12_FILTER_MIN_LINEAR_MAG_MIP_POINT, "MIN_LINEAR_MAG_MIP_POINT" },
	{ D3D12_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR, "MIN_LINEAR_MAG_POINT_MIP_LINEAR" },
	{ D3D12_FILTER_MIN_MAG_LINEAR_MIP_POINT, "MIN_MAG_LINEAR_MIP_POINT" },
	{ D3D12_FILTER_MIN_MAG_MIP_LINEAR, "MIN_MAG_MIP_LINEAR" },
	{ D3D12_FILTER_MIN_MAG_ANISOTROPIC_MIP_POINT, "MIN_MAG_ANISOTROPIC_MIP_POINT" },
	{ D3D12_FILTER_ANISOTROPIC, "ANISOTROPIC" },
	{ D3D12_FILTER_COMPARISON_MIN_MAG_MIP_POINT, "COMPARISON_MIN_MAG_MIP_POINT" },
	{ D3D12_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR, "COMPARISON_MIN_MAG_POINT_MIP_LINEAR" },
	{ D3D12_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT, "COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT" },
	{ D3D12_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR, "COMPARISON_MIN_POINT_MAG_MIP_LINEAR" },
	{ D3D12_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT, "COMPARISON_MIN_LINEAR_MAG_MIP_POINT" },
	{ D3D12_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR, "COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR" },
	{ D3D12_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT, "COMPARISON_MIN_MAG_LINEAR_MIP_POINT" },
	{ D3D12_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR, "COMPARISON_MIN_MAG_MIP_LINEAR" },
	{ D3D12_FILTER_COMPARISON_MIN_MAG_ANISOTROPIC_MIP_POINT, "COMPARISON_MIN_MAG_ANISOTROPIC_MIP_POINT" },
	{ D3D12_FILTER_COMPARISON_ANISOTROPIC, "COMPARISON_ANISOTROPIC" },
	{ D3D12_FILTER_MINIMUM_MIN_MAG_MIP_POINT, "MINIMUM_MIN_MAG_MIP_POINT" },
	{ D3D12_FILTER_MINIMUM_MIN_MAG_POINT_MIP_LINEAR, "MINIMUM_MIN_MAG_POINT_MIP_LINEAR" },
	{ D3D12_FILTER_MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT, "MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT" },
	{ D3D12_FILTER_MINIMUM_MIN_POINT_MAG_MIP_LINEAR, "MINIMUM_MIN_POINT_MAG_MIP_LINEAR" },
	{ D3D12_FILTER_MINIMUM_MIN_LINEAR_MAG_MIP_POINT, "MINIMUM_MIN_LINEAR_MAG_MIP_POINT" },
	{ D3D12_FILTER_MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR, "MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR" },
	{ D3D12_FILTER_MINIMUM_MIN_MAG_LINEAR_MIP_POINT, "MINIMUM_MIN_MAG_LINEAR_MIP_POINT" },
	{ D3D12_FILTER_MINIMUM_MIN_MAG_MIP_LINEAR, "MINIMUM_MIN_MAG_MIP_LINEAR" },
	{ D3D12_FILTER_MINIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT, "MINIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT" },
	{ D3D12_FILTER_MINIMUM_ANISOTROPIC, "MINIMUM_ANISOTROPIC" },
	{ D3D12_FILTER_MAXIMUM_MIN_MAG_MIP_POINT, "MAXIMUM_MIN_MAG_MIP_POINT" },
	{ D3D12_FILTER_MAXIMUM_MIN_MAG_POINT_MIP_LINEAR, "MAXIMUM_MIN_MAG_POINT_MIP_LINEAR" },
	{ D3D12_FILTER_MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT, "MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT" },
	{ D3D12_FILTER_MAXIMUM_MIN_POINT_MAG_MIP_LINEAR, "MAXIMUM_MIN_POINT_MAG_MIP_LINEAR" },
	{ D3D12_FILTER_MAXIMUM_MIN_LINEAR_MAG_MIP_POINT, "MAXIMUM_MIN_LINEAR_MAG_MIP_POINT" },
	{ D3D12_FILTER_MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR, "MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR" },
	{ D3D12_FILTER_MAXIMUM_MIN_MAG_LINEAR_MIP_POINT, "MAXIMUM_MIN_MAG_LINEAR_MIP_POINT" },
	{ D3D12_FILTER_MAXIMUM_MIN_MAG_MIP_LINEAR, "MAXIMUM_MIN_MAG_MIP_LINEAR" },
	{ D3D12_FILTER_MAXIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT, "MAXIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT" },
	{ D3D12_FILTER_MAXIMUM_ANISOTROPIC, "MAXIMUM_ANISOTROPIC" }
};

static inline std::unordered_map<std::string, D3D12_FILTER> StringToD3D12_FILTER = {
	{ "MIN_MAG_MIP_POINT", D3D12_FILTER_MIN_MAG_MIP_POINT },
	{ "MIN_MAG_POINT_MIP_LINEAR", D3D12_FILTER_MIN_MAG_POINT_MIP_LINEAR },
	{ "MIN_POINT_MAG_LINEAR_MIP_POINT", D3D12_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT },
	{ "MIN_POINT_MAG_MIP_LINEAR", D3D12_FILTER_MIN_POINT_MAG_MIP_LINEAR },
	{ "MIN_LINEAR_MAG_MIP_POINT", D3D12_FILTER_MIN_LINEAR_MAG_MIP_POINT },
	{ "MIN_LINEAR_MAG_POINT_MIP_LINEAR", D3D12_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR },
	{ "MIN_MAG_LINEAR_MIP_POINT", D3D12_FILTER_MIN_MAG_LINEAR_MIP_POINT },
	{ "MIN_MAG_MIP_LINEAR", D3D12_FILTER_MIN_MAG_MIP_LINEAR },
	{ "MIN_MAG_ANISOTROPIC_MIP_POINT", D3D12_FILTER_MIN_MAG_ANISOTROPIC_MIP_POINT },
	{ "ANISOTROPIC", D3D12_FILTER_ANISOTROPIC },
	{ "COMPARISON_MIN_MAG_MIP_POINT", D3D12_FILTER_COMPARISON_MIN_MAG_MIP_POINT },
	{ "COMPARISON_MIN_MAG_POINT_MIP_LINEAR", D3D12_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR },
	{ "COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT", D3D12_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT },
	{ "COMPARISON_MIN_POINT_MAG_MIP_LINEAR", D3D12_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR },
	{ "COMPARISON_MIN_LINEAR_MAG_MIP_POINT", D3D12_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT },
	{ "COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR", D3D12_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR },
	{ "COMPARISON_MIN_MAG_LINEAR_MIP_POINT", D3D12_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT },
	{ "COMPARISON_MIN_MAG_MIP_LINEAR", D3D12_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR },
	{ "COMPARISON_MIN_MAG_ANISOTROPIC_MIP_POINT", D3D12_FILTER_COMPARISON_MIN_MAG_ANISOTROPIC_MIP_POINT },
	{ "COMPARISON_ANISOTROPIC", D3D12_FILTER_COMPARISON_ANISOTROPIC },
	{ "MINIMUM_MIN_MAG_MIP_POINT", D3D12_FILTER_MINIMUM_MIN_MAG_MIP_POINT },
	{ "MINIMUM_MIN_MAG_POINT_MIP_LINEAR", D3D12_FILTER_MINIMUM_MIN_MAG_POINT_MIP_LINEAR },
	{ "MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT", D3D12_FILTER_MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT },
	{ "MINIMUM_MIN_POINT_MAG_MIP_LINEAR", D3D12_FILTER_MINIMUM_MIN_POINT_MAG_MIP_LINEAR },
	{ "MINIMUM_MIN_LINEAR_MAG_MIP_POINT", D3D12_FILTER_MINIMUM_MIN_LINEAR_MAG_MIP_POINT },
	{ "MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR", D3D12_FILTER_MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR },
	{ "MINIMUM_MIN_MAG_LINEAR_MIP_POINT", D3D12_FILTER_MINIMUM_MIN_MAG_LINEAR_MIP_POINT },
	{ "MINIMUM_MIN_MAG_MIP_LINEAR", D3D12_FILTER_MINIMUM_MIN_MAG_MIP_LINEAR },
	{ "MINIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT", D3D12_FILTER_MINIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT },
	{ "MINIMUM_ANISOTROPIC", D3D12_FILTER_MINIMUM_ANISOTROPIC },
	{ "MAXIMUM_MIN_MAG_MIP_POINT", D3D12_FILTER_MAXIMUM_MIN_MAG_MIP_POINT },
	{ "MAXIMUM_MIN_MAG_POINT_MIP_LINEAR", D3D12_FILTER_MAXIMUM_MIN_MAG_POINT_MIP_LINEAR },
	{ "MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT", D3D12_FILTER_MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT },
	{ "MAXIMUM_MIN_POINT_MAG_MIP_LINEAR", D3D12_FILTER_MAXIMUM_MIN_POINT_MAG_MIP_LINEAR },
	{ "MAXIMUM_MIN_LINEAR_MAG_MIP_POINT", D3D12_FILTER_MAXIMUM_MIN_LINEAR_MAG_MIP_POINT },
	{ "MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR", D3D12_FILTER_MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR },
	{ "MAXIMUM_MIN_MAG_LINEAR_MIP_POINT", D3D12_FILTER_MAXIMUM_MIN_MAG_LINEAR_MIP_POINT },
	{ "MAXIMUM_MIN_MAG_MIP_LINEAR", D3D12_FILTER_MAXIMUM_MIN_MAG_MIP_LINEAR },
	{ "MAXIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT", D3D12_FILTER_MAXIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT },
	{ "MAXIMUM_ANISOTROPIC", D3D12_FILTER_MAXIMUM_ANISOTROPIC }
};

static inline std::unordered_map<D3D12_TEXTURE_ADDRESS_MODE, std::string> D3D12_TEXTURE_ADDRESS_MODEToString = {
	{ D3D12_TEXTURE_ADDRESS_MODE_WRAP, "ADDRESS_MODE_WRAP" },
	{ D3D12_TEXTURE_ADDRESS_MODE_MIRROR, "ADDRESS_MODE_MIRROR" },
	{ D3D12_TEXTURE_ADDRESS_MODE_CLAMP, "ADDRESS_MODE_CLAMP" },
	{ D3D12_TEXTURE_ADDRESS_MODE_BORDER, "ADDRESS_MODE_BORDER" },
	{ D3D12_TEXTURE_ADDRESS_MODE_MIRROR_ONCE, "ADDRESS_MODE_MIRROR_ONCE" }
};

static inline std::unordered_map<std::string, D3D12_TEXTURE_ADDRESS_MODE> StringToD3D12_TEXTURE_ADDRESS_MODE = {
	{ "ADDRESS_MODE_WRAP", D3D12_TEXTURE_ADDRESS_MODE_WRAP },
	{ "ADDRESS_MODE_MIRROR", D3D12_TEXTURE_ADDRESS_MODE_MIRROR },
	{ "ADDRESS_MODE_CLAMP", D3D12_TEXTURE_ADDRESS_MODE_CLAMP },
	{ "ADDRESS_MODE_BORDER", D3D12_TEXTURE_ADDRESS_MODE_BORDER },
	{ "ADDRESS_MODE_MIRROR_ONCE", D3D12_TEXTURE_ADDRESS_MODE_MIRROR_ONCE }
};

static inline std::unordered_map<D3D12_COMPARISON_FUNC, std::string> D3D12_COMPARISON_FUNCToString = {
	{ D3D12_COMPARISON_FUNC_NONE, "NONE" },
	{ D3D12_COMPARISON_FUNC_NEVER, "NEVER" },
	{ D3D12_COMPARISON_FUNC_LESS, "LESS" },
	{ D3D12_COMPARISON_FUNC_EQUAL, "EQUAL" },
	{ D3D12_COMPARISON_FUNC_LESS_EQUAL, "LESS_EQUAL" },
	{ D3D12_COMPARISON_FUNC_GREATER, "GREATER" },
	{ D3D12_COMPARISON_FUNC_NOT_EQUAL, "NOT_EQUAL" },
	{ D3D12_COMPARISON_FUNC_GREATER_EQUAL, "GREATER_EQUAL" },
	{ D3D12_COMPARISON_FUNC_ALWAYS, "ALWAYS" }
};

static inline std::unordered_map<std::string, D3D12_COMPARISON_FUNC> StringToD3D12_COMPARISON_FUNC = {
	{ "NONE", D3D12_COMPARISON_FUNC_NONE },
	{ "NEVER", D3D12_COMPARISON_FUNC_NEVER },
	{ "LESS", D3D12_COMPARISON_FUNC_LESS },
	{ "EQUAL", D3D12_COMPARISON_FUNC_EQUAL },
	{ "LESS_EQUAL", D3D12_COMPARISON_FUNC_LESS_EQUAL },
	{ "GREATER", D3D12_COMPARISON_FUNC_GREATER },
	{ "NOT_EQUAL", D3D12_COMPARISON_FUNC_NOT_EQUAL },
	{ "GREATER_EQUAL", D3D12_COMPARISON_FUNC_GREATER_EQUAL },
	{ "ALWAYS", D3D12_COMPARISON_FUNC_ALWAYS }
};

static inline std::unordered_map<D3D12_STATIC_BORDER_COLOR, std::string> D3D12_STATIC_BORDER_COLORToString = {
	{ D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK, "TRANSPARENT_BLACK" },
	{ D3D12_STATIC_BORDER_COLOR_OPAQUE_BLACK, "OPAQUE_BLACK" },
	{ D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE, "OPAQUE_WHITE" },
	{ D3D12_STATIC_BORDER_COLOR_OPAQUE_BLACK_UINT, "OPAQUE_BLACK_UINT" },
	{ D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE_UINT, "OPAQUE_WHITE_UINT" }
};

static inline std::unordered_map<std::string, D3D12_STATIC_BORDER_COLOR> StringToD3D12_STATIC_BORDER_COLOR = {
	{ "TRANSPARENT_BLACK", D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK },
	{ "OPAQUE_BLACK", D3D12_STATIC_BORDER_COLOR_OPAQUE_BLACK },
	{ "OPAQUE_WHITE", D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE },
	{ "OPAQUE_BLACK_UINT", D3D12_STATIC_BORDER_COLOR_OPAQUE_BLACK_UINT },
	{ "OPAQUE_WHITE_UINT", D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE_UINT }
};

static inline std::unordered_map<D3D12_SHADER_VISIBILITY, std::string> D3D12_SHADER_VISIBILITYToString = {
	{ D3D12_SHADER_VISIBILITY_ALL, "ALL" },
	{ D3D12_SHADER_VISIBILITY_VERTEX, "VERTEX" },
	{ D3D12_SHADER_VISIBILITY_HULL, "HULL" },
	{ D3D12_SHADER_VISIBILITY_DOMAIN, "DOMAIN" },
	{ D3D12_SHADER_VISIBILITY_GEOMETRY, "GEOMETRY" },
	{ D3D12_SHADER_VISIBILITY_PIXEL, "PIXEL" },
	{ D3D12_SHADER_VISIBILITY_AMPLIFICATION, "AMPLIFICATION" },
	{ D3D12_SHADER_VISIBILITY_MESH, "MESH" }
};

static inline std::unordered_map<std::string, D3D12_SHADER_VISIBILITY> StringToD3D12_SHADER_VISIBILITY = {
	{ "ALL", D3D12_SHADER_VISIBILITY_ALL},
	{ "VERTEX", D3D12_SHADER_VISIBILITY_VERTEX },
	{ "HULL", D3D12_SHADER_VISIBILITY_HULL },
	{ "DOMAIN", D3D12_SHADER_VISIBILITY_DOMAIN },
	{ "GEOMETRY", D3D12_SHADER_VISIBILITY_GEOMETRY },
	{ "PIXEL", D3D12_SHADER_VISIBILITY_PIXEL },
	{ "AMPLIFICATION", D3D12_SHADER_VISIBILITY_AMPLIFICATION },
	{ "MESH", D3D12_SHADER_VISIBILITY_MESH }
};

static inline std::unordered_map<D3D_PRIMITIVE_TOPOLOGY, std::string> D3D_PRIMITIVE_TOPOLOGYToString = {
	{ D3D_PRIMITIVE_TOPOLOGY_UNDEFINED , "UNDEFINED" },
	{ D3D_PRIMITIVE_TOPOLOGY_POINTLIST , "POINTLIST" },
	{ D3D_PRIMITIVE_TOPOLOGY_LINELIST , "LINELIST" },
	{ D3D_PRIMITIVE_TOPOLOGY_LINESTRIP , "LINESTRIP" },
	{ D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST , "TRIANGLELIST" },
	{ D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP , "TRIANGLESTRIP" },
	{ D3D_PRIMITIVE_TOPOLOGY_TRIANGLEFAN , "TRIANGLEFAN" },
	{ D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ , "LINELIST_ADJ" },
	{ D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ , "LINESTRIP_ADJ" },
	{ D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ , "TRIANGLELIST_ADJ" },
	{ D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ , "TRIANGLESTRIP_ADJ" },
};

static inline std::unordered_map<std::string, D3D_PRIMITIVE_TOPOLOGY> StringToD3D_PRIMITIVE_TOPOLOGY = {
	{ "UNDEFINED", D3D_PRIMITIVE_TOPOLOGY_UNDEFINED },
	{ "POINTLIST", D3D_PRIMITIVE_TOPOLOGY_POINTLIST },
	{ "LINELIST", D3D_PRIMITIVE_TOPOLOGY_LINELIST },
	{ "LINESTRIP", D3D_PRIMITIVE_TOPOLOGY_LINESTRIP },
	{ "TRIANGLELIST", D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST },
	{ "TRIANGLESTRIP", D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP },
	{ "TRIANGLEFAN", D3D_PRIMITIVE_TOPOLOGY_TRIANGLEFAN },
	{ "LINELIST_ADJ", D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ },
	{ "LINESTRIP_ADJ", D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ },
	{ "TRIANGLELIST_ADJ", D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ },
	{ "TRIANGLESTRIP_ADJ", D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ },
};

static inline std::unordered_map<D3D12_PRIMITIVE_TOPOLOGY_TYPE, std::string> D3D12_PRIMITIVE_TOPOLOGY_TYPEToString = {
	{ D3D12_PRIMITIVE_TOPOLOGY_TYPE_UNDEFINED, "UNDEFINED" },
	{ D3D12_PRIMITIVE_TOPOLOGY_TYPE_POINT, "POINT" },
	{ D3D12_PRIMITIVE_TOPOLOGY_TYPE_LINE, "LINE" },
	{ D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE, "TRIANGLE" },
	{ D3D12_PRIMITIVE_TOPOLOGY_TYPE_PATCH, "PATCH" },
};

static inline std::unordered_map<std::string, D3D12_PRIMITIVE_TOPOLOGY_TYPE> StringToD3D12_PRIMITIVE_TOPOLOGY_TYPE = {
	{ "UNDEFINED", D3D12_PRIMITIVE_TOPOLOGY_TYPE_UNDEFINED },
	{ "POINT", D3D12_PRIMITIVE_TOPOLOGY_TYPE_POINT },
	{ "LINE", D3D12_PRIMITIVE_TOPOLOGY_TYPE_LINE },
	{ "TRIANGLE", D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE },
	{ "PATCH", D3D12_PRIMITIVE_TOPOLOGY_TYPE_PATCH },
};

static inline std::unordered_map<D3D12_PRIMITIVE_TOPOLOGY_TYPE, D3D_PRIMITIVE_TOPOLOGY> D3D12_PRIMITIVE_TOPOLOGY_TYPEToD3D_PRIMITIVE_TOPOLOGY = {
	{ D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE , D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST },
	{ D3D12_PRIMITIVE_TOPOLOGY_TYPE_LINE, D3D_PRIMITIVE_TOPOLOGY_LINELIST }
};

static inline std::unordered_map<D3D_PRIMITIVE_TOPOLOGY, D3D12_PRIMITIVE_TOPOLOGY_TYPE> D3D_PRIMITIVE_TOPOLOGYToD3D12_PRIMITIVE_TOPOLOGY_TYPE = {
	{ D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST, D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE },
	{ D3D_PRIMITIVE_TOPOLOGY_LINELIST, D3D12_PRIMITIVE_TOPOLOGY_TYPE_LINE }
};

static inline std::unordered_map<D3D12_FILL_MODE, std::string> D3D12_FILL_MODEToString = {
	{ D3D12_FILL_MODE_WIREFRAME, "WIREFRAME" },
	{ D3D12_FILL_MODE_SOLID, "SOLID" },
};

static inline std::unordered_map<std::string, D3D12_FILL_MODE> StringToD3D12_FILL_MODE = {
	{ "WIREFRAME", D3D12_FILL_MODE_WIREFRAME },
	{ "SOLID", D3D12_FILL_MODE_SOLID },
};

static inline std::unordered_map<D3D12_CULL_MODE, std::string> D3D12_CULL_MODEToString = {
	{ D3D12_CULL_MODE_NONE, "NONE" },
	{ D3D12_CULL_MODE_FRONT, "FRONT" },
	{ D3D12_CULL_MODE_BACK, "BACK" }
};

static inline std::unordered_map<std::string, D3D12_CULL_MODE> StringToD3D12_CULL_MODE = {
	{ "NONE",	D3D12_CULL_MODE_NONE },
	{ "FRONT", D3D12_CULL_MODE_FRONT },
	{ "BACK", D3D12_CULL_MODE_BACK },
};

static inline std::unordered_map<D3D12_CONSERVATIVE_RASTERIZATION_MODE, std::string> D3D12_CONSERVATIVE_RASTERIZATION_MODEToString = {
	{ D3D12_CONSERVATIVE_RASTERIZATION_MODE_OFF , "OFF" },
	{ D3D12_CONSERVATIVE_RASTERIZATION_MODE_ON, "ON" },
};

static inline std::unordered_map<std::string, D3D12_CONSERVATIVE_RASTERIZATION_MODE> StringToD3D12_CONSERVATIVE_RASTERIZATION_MODE = {
	{ "OFF", D3D12_CONSERVATIVE_RASTERIZATION_MODE_OFF },
	{ "ON", D3D12_CONSERVATIVE_RASTERIZATION_MODE_ON },
};

static inline std::unordered_map<D3D12_BLEND, std::string> D3D12_BLENDToString =
{
	{ D3D12_BLEND_ZERO, "ZERO" },
	{ D3D12_BLEND_ONE, "ONE" },
	{ D3D12_BLEND_SRC_COLOR, "SRC_COLOR" },
	{ D3D12_BLEND_INV_SRC_COLOR, "INV_SRC_COLOR" },
	{ D3D12_BLEND_SRC_ALPHA, "SRC_ALPHA" },
	{ D3D12_BLEND_INV_SRC_ALPHA, "INV_SRC_ALPHA" },
	{ D3D12_BLEND_DEST_ALPHA, "DEST_ALPHA" },
	{ D3D12_BLEND_INV_DEST_ALPHA, "INV_DEST_ALPHA" },
	{ D3D12_BLEND_DEST_COLOR, "DEST_COLOR" },
	{ D3D12_BLEND_INV_DEST_COLOR , "INV_DEST_COLOR" },
	{ D3D12_BLEND_SRC_ALPHA_SAT , "SRC_ALPHA_SAT" },
	{ D3D12_BLEND_BLEND_FACTOR , "BLEND_FACTOR" },
	{ D3D12_BLEND_INV_BLEND_FACTOR , "INV_BLEND_FACTOR" },
	{ D3D12_BLEND_SRC1_COLOR , "SRC1_COLOR" },
	{ D3D12_BLEND_INV_SRC1_COLOR , "INV_SRC1_COLOR" },
	{ D3D12_BLEND_SRC1_ALPHA , "SRC1_ALPHA" },
	{ D3D12_BLEND_INV_SRC1_ALPHA , "INV_SRC1_ALPHA" },
	{ D3D12_BLEND_ALPHA_FACTOR , "ALPHA_FACTOR" },
	{ D3D12_BLEND_INV_ALPHA_FACTOR, "INV_ALPHA_FACTOR" },
};

static inline std::unordered_map<std::string, D3D12_BLEND> StringToD3D12_BLEND =
{
	{ "ZERO", D3D12_BLEND_ZERO},
	{ "ONE", D3D12_BLEND_ONE},
	{ "SRC_COLOR",  D3D12_BLEND_SRC_COLOR},
	{ "INV_SRC_COLOR", D3D12_BLEND_INV_SRC_COLOR},
	{ "SRC_ALPHA", D3D12_BLEND_SRC_ALPHA},
	{ "INV_SRC_ALPHA", D3D12_BLEND_INV_SRC_ALPHA},
	{ "DEST_ALPHA", D3D12_BLEND_DEST_ALPHA},
	{ "INV_DEST_ALPHA", D3D12_BLEND_INV_DEST_ALPHA},
	{ "DEST_COLOR", D3D12_BLEND_DEST_COLOR},
	{ "INV_DEST_COLOR", D3D12_BLEND_INV_DEST_COLOR },
	{ "SRC_ALPHA_SAT", D3D12_BLEND_SRC_ALPHA_SAT },
	{ "BLEND_FACTOR", D3D12_BLEND_BLEND_FACTOR },
	{ "INV_BLEND_FACTOR", D3D12_BLEND_INV_BLEND_FACTOR },
	{ "SRC1_COLOR", D3D12_BLEND_SRC1_COLOR },
	{ "INV_SRC1_COLOR", D3D12_BLEND_INV_SRC1_COLOR },
	{ "SRC1_ALPHA", D3D12_BLEND_SRC1_ALPHA },
	{ "INV_SRC1_ALPHA", D3D12_BLEND_INV_SRC1_ALPHA },
	{ "ALPHA_FACTOR", D3D12_BLEND_ALPHA_FACTOR },
	{ "INV_ALPHA_FACTOR", D3D12_BLEND_INV_ALPHA_FACTOR },
};

static inline std::unordered_map<D3D12_BLEND_OP, std::string> D3D12_BLEND_OPToString =
{
	{ D3D12_BLEND_OP_ADD, "ADD" },
	{ D3D12_BLEND_OP_SUBTRACT, "SUBTRACT" },
	{ D3D12_BLEND_OP_REV_SUBTRACT, "REV_SUBTRACT" },
	{ D3D12_BLEND_OP_MIN, "MIN" },
	{ D3D12_BLEND_OP_MAX, "MAX" },
};

static inline std::unordered_map<std::string, D3D12_BLEND_OP> StringToD3D12_BLEND_OP =
{
	{ "ADD", D3D12_BLEND_OP_ADD },
	{ "SUBTRACT", D3D12_BLEND_OP_SUBTRACT },
	{ "REV_SUBTRACT", D3D12_BLEND_OP_REV_SUBTRACT },
	{ "MIN", D3D12_BLEND_OP_MIN },
	{ "MAX", D3D12_BLEND_OP_MAX },
};

static inline std::unordered_map<D3D12_LOGIC_OP, std::string> D3D12_LOGIC_OPToString =
{
	{ D3D12_LOGIC_OP_CLEAR, "CLEAR" },
	{ D3D12_LOGIC_OP_SET, "SET" },
	{ D3D12_LOGIC_OP_COPY, "COPY" },
	{ D3D12_LOGIC_OP_COPY_INVERTED, "COPY_INVERTED" },
	{ D3D12_LOGIC_OP_NOOP, "NOOP" },
	{ D3D12_LOGIC_OP_INVERT, "INVERT" },
	{ D3D12_LOGIC_OP_AND, "AND" },
	{ D3D12_LOGIC_OP_NAND, "NAND" },
	{ D3D12_LOGIC_OP_OR, "OR" },
	{ D3D12_LOGIC_OP_NOR, "NOR" },
	{ D3D12_LOGIC_OP_XOR, "XOR" },
	{ D3D12_LOGIC_OP_EQUIV, "EQUIV" },
	{ D3D12_LOGIC_OP_AND_REVERSE, "AND_REVERSE" },
	{ D3D12_LOGIC_OP_AND_INVERTED, "AND_INVERTED" },
	{ D3D12_LOGIC_OP_OR_REVERSE, "OR_REVERSE" },
	{ D3D12_LOGIC_OP_OR_INVERTED, "OR_INVERTED" },
};

static inline std::unordered_map<std::string, D3D12_LOGIC_OP> StringToD3D12_LOGIC_OP =
{
	{ "CLEAR", D3D12_LOGIC_OP_CLEAR },
	{ "SET", D3D12_LOGIC_OP_SET },
	{ "COPY", D3D12_LOGIC_OP_COPY },
	{ "COPY_INVERTED", D3D12_LOGIC_OP_COPY_INVERTED },
	{ "NOOP", D3D12_LOGIC_OP_NOOP },
	{ "INVERT", D3D12_LOGIC_OP_INVERT },
	{ "AND", D3D12_LOGIC_OP_AND },
	{ "NAND", D3D12_LOGIC_OP_NAND },
	{ "OR", D3D12_LOGIC_OP_OR },
	{ "NOR", D3D12_LOGIC_OP_NOR },
	{ "XOR", D3D12_LOGIC_OP_XOR },
	{ "EQUIV", D3D12_LOGIC_OP_EQUIV },
	{ "AND_REVERSE", D3D12_LOGIC_OP_AND_REVERSE },
	{ "AND_INVERTED", D3D12_LOGIC_OP_AND_INVERTED },
	{ "OR_REVERSE", D3D12_LOGIC_OP_OR_REVERSE },
	{ "OR_INVERTED", D3D12_LOGIC_OP_OR_INVERTED },
};

static inline std::unordered_map<D3D_SHADER_INPUT_TYPE, std::string> D3D_SHADER_INPUT_TYPEToString =
{
	{ D3D_SIT_CBUFFER, "CBUFFER" },
	{ D3D_SIT_TBUFFER, "TBUFFER" },
	{ D3D_SIT_TEXTURE, "TEXTURE" },
	{ D3D_SIT_SAMPLER, "SAMPLER" },
	{ D3D_SIT_UAV_RWTYPED, "UAV_RWTYPED" },
	{ D3D_SIT_STRUCTURED, "STRUCTURED" },
	{ D3D_SIT_UAV_RWSTRUCTURED, "UAV_RWSTRUCTURED" },
	{ D3D_SIT_BYTEADDRESS, "BYTEADDRESS" },
	{ D3D_SIT_UAV_RWBYTEADDRESS, "UAV_RWBYTEADDRESS" },
	{ D3D_SIT_UAV_APPEND_STRUCTURED, "UAV_APPEND_STRUCTURED" },
	{ D3D_SIT_UAV_CONSUME_STRUCTURED, "UAV_CONSUME_STRUCTURED" },
	{ D3D_SIT_UAV_RWSTRUCTURED_WITH_COUNTER, "UAV_RWSTRUCTURED_WITH_COUNTER" },
	{ D3D_SIT_RTACCELERATIONSTRUCTURE, "RTACCELERATIONSTRUCTURE" },
	{ D3D_SIT_UAV_FEEDBACKTEXTURE, "UAV_FEEDBACKTEXTURE" },
};

static inline std::unordered_map<std::string, D3D_SHADER_INPUT_TYPE> StringToD3D_SHADER_INPUT_TYPE =
{
	{ "CBUFFER", D3D_SIT_CBUFFER },
	{ "TBUFFER", D3D_SIT_TBUFFER },
	{ "TEXTURE", D3D_SIT_TEXTURE },
	{ "SAMPLER", D3D_SIT_SAMPLER },
	{ "UAV_RWTYPED", D3D_SIT_UAV_RWTYPED },
	{ "STRUCTURED", D3D_SIT_STRUCTURED },
	{ "UAV_RWSTRUCTURED", D3D_SIT_UAV_RWSTRUCTURED },
	{ "BYTEADDRESS", D3D_SIT_BYTEADDRESS },
	{ "UAV_RWBYTEADDRESS", D3D_SIT_UAV_RWBYTEADDRESS },
	{ "UAV_APPEND_STRUCTURED", D3D_SIT_UAV_APPEND_STRUCTURED },
	{ "UAV_CONSUME_STRUCTURED", D3D_SIT_UAV_CONSUME_STRUCTURED },
	{ "UAV_RWSTRUCTURED_WITH_COUNTER", D3D_SIT_UAV_RWSTRUCTURED_WITH_COUNTER },
	{ "RTACCELERATIONSTRUCTURE", D3D_SIT_RTACCELERATIONSTRUCTURE },
	{ "UAV_FEEDBACKTEXTURE", D3D_SIT_UAV_FEEDBACKTEXTURE},
};

static inline std::unordered_map<SOUND_EFFECT_INSTANCE_FLAGS, std::string> SOUND_EFFECT_INSTANCE_FLAGSToString =
{
	{ SoundEffectInstance_Use3D , "Use3D"},
	{ SoundEffectInstance_ReverbUseFilters ,"ReverbUseFilters"},
	{ SoundEffectInstance_NoSetPitch , "NoSetPitch"},
};

static inline std::unordered_map<std::string, SOUND_EFFECT_INSTANCE_FLAGS> StringToSOUND_EFFECT_INSTANCE_FLAGS =
{
	{ "Use3D", SoundEffectInstance_Use3D },
	{ "ReverbUseFilters", SoundEffectInstance_ReverbUseFilters },
	{ "NoSetPitch", SoundEffectInstance_NoSetPitch },
};

static inline std::unordered_map<AUDIO_ENGINE_REVERB, std::string> AUDIO_ENGINE_REVERBToString =
{
	{ Reverb_Off, "Off" },
	{ Reverb_Default, "Default" },
	{ Reverb_Generic, "Generic" },
	{ Reverb_Forest, "Forest" },
	{ Reverb_PaddedCell, "PaddedCell" },
	{ Reverb_Room, "Room" },
	{ Reverb_Bathroom, "Bathroom" },
	{ Reverb_LivingRoom, "LivingRoom" },
	{ Reverb_StoneRoom, "StoneRoom" },
	{ Reverb_Auditorium, "Auditorium" },
	{ Reverb_ConcertHall, "ConcertHall" },
	{ Reverb_Cave, "Cave" },
	{ Reverb_Arena, "Arena" },
	{ Reverb_Hangar, "Hangar" },
	{ Reverb_CarpetedHallway, "CarpetedHallway" },
	{ Reverb_Hallway, "Hallway" },
	{ Reverb_StoneCorridor, "StoneCorridor" },
	{ Reverb_Alley, "Alley" },
	{ Reverb_City, "City" },
	{ Reverb_Mountains, "Mountains" },
	{ Reverb_Quarry, "Quarry" },
	{ Reverb_Plain, "Plain" },
	{ Reverb_ParkingLot, "ParkingLot" },
	{ Reverb_SewerPipe, "SewerPipe" },
	{ Reverb_Underwater, "Underwater" },
	{ Reverb_SmallRoom, "SmallRoom" },
	{ Reverb_MediumRoom, "MediumRoom" },
	{ Reverb_LargeRoom, "LargeRoom" },
	{ Reverb_MediumHall, "MediumHall" },
	{ Reverb_LargeHall, "LargeHall" },
	{ Reverb_Plate, "Plate" },
};

static inline std::unordered_map<std::string, AUDIO_ENGINE_REVERB> StringToAUDIO_ENGINE_REVERB =
{
	{ "Off", Reverb_Off },
	{ "Default", Reverb_Default },
	{ "Generic", Reverb_Generic },
	{ "Forest", Reverb_Forest },
	{ "PaddedCell", Reverb_PaddedCell },
	{ "Room", Reverb_Room },
	{ "Bathroom", Reverb_Bathroom },
	{ "LivingRoom", Reverb_LivingRoom },
	{ "StoneRoom", Reverb_StoneRoom },
	{ "Auditorium", Reverb_Auditorium },
	{ "ConcertHall", Reverb_ConcertHall },
	{ "Cave", Reverb_Cave },
	{ "Arena", Reverb_Arena },
	{ "Hangar", Reverb_Hangar },
	{ "CarpetedHallway", Reverb_CarpetedHallway },
	{ "Hallway", Reverb_Hallway },
	{ "StoneCorridor", Reverb_StoneCorridor },
	{ "Alley", Reverb_Alley },
	{ "City", Reverb_City },
	{ "Mountains", Reverb_Mountains },
	{ "Quarry", Reverb_Quarry },
	{ "Plain", Reverb_Plain },
	{ "ParkingLot", Reverb_ParkingLot },
	{ "SewerPipe", Reverb_SewerPipe },
	{ "Underwater", Reverb_Underwater },
	{ "SmallRoom", Reverb_SmallRoom },
	{ "MediumRoom", Reverb_MediumRoom },
	{ "LargeRoom", Reverb_LargeRoom },
	{ "MediumHall", Reverb_MediumHall },
	{ "LargeHall", Reverb_LargeHall },
	{ "Plate", Reverb_Plate },
};

static inline std::unordered_map<D3D12_DEPTH_WRITE_MASK, std::string> D3D12_DEPTH_WRITE_MASKToString = {
	{ D3D12_DEPTH_WRITE_MASK_ZERO , "ZERO" },
	{ D3D12_DEPTH_WRITE_MASK_ALL , "ALL" },
};

static inline std::unordered_map<std::string, D3D12_DEPTH_WRITE_MASK> StringToD3D12_DEPTH_WRITE_MASK = {
	{ "ZERO", D3D12_DEPTH_WRITE_MASK_ZERO },
	{ "ALL", D3D12_DEPTH_WRITE_MASK_ALL },
};

static inline std::unordered_map<D3D12_STENCIL_OP, std::string> D3D12_STENCIL_OPToString = {
	{ D3D12_STENCIL_OP_KEEP , "KEEP" },
	{ D3D12_STENCIL_OP_ZERO , "ZERO" },
	{ D3D12_STENCIL_OP_REPLACE , "REPLACE" },
	{ D3D12_STENCIL_OP_INCR_SAT , "INCR_SAT" },
	{ D3D12_STENCIL_OP_DECR_SAT , "DECR_SAT" },
	{ D3D12_STENCIL_OP_INVERT , "INVERT" },
	{ D3D12_STENCIL_OP_INCR , "INCR" },
	{ D3D12_STENCIL_OP_DECR , "DECR" },
};

static inline std::unordered_map<std::string, D3D12_STENCIL_OP> StringToD3D12_STENCIL_OP = {
	{ "KEEP", D3D12_STENCIL_OP_KEEP },
	{ "ZERO", D3D12_STENCIL_OP_ZERO },
	{ "REPLACE", D3D12_STENCIL_OP_REPLACE },
	{ "INCR_SAT", D3D12_STENCIL_OP_INCR_SAT },
	{ "DECR_SAT", D3D12_STENCIL_OP_DECR_SAT },
	{ "INVERT", D3D12_STENCIL_OP_INVERT },
	{ "INCR", D3D12_STENCIL_OP_INCR },
	{ "DECR", D3D12_STENCIL_OP_DECR },
};