JCLASS(BrawlerScene, _)
JEXPOSE(std::string, venomUI, "", jedv_t_te_htmlui, 1, false)
//JEXPOSE_TRANSFORM(XMFLOAT3, thugAttackOffsetVector, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(1.0f, 0.0f, 0.0f), jedv_t_float3, 1, false)
JEXPOSE(JUUID, venomUIInstance, "", jedv_t_hidden, 0, false)
JEXPOSE_SET(JUUID, heroes, {}, jedv_t_hidden, 0, false)
JEXPOSE_SET(JUUID, ready_heroes, {}, jedv_t_hidden, 0, false)
JEXPOSE_SET(JUUID, enemies, {}, jedv_t_hidden, 0, false)
JEXPOSE(unsigned int, currentRound, 0U, jedv_t_unsigned, 0, false)
JEXPOSE(unsigned int, enemiesInCurrentRound, 0U, jedv_t_unsigned, 0, false)
JEXPOSE(bool, heroHealthChanged, true, jedv_t_hidden, 0, false)
JEXPOSE(int, heroHealth, 100, jedv_t_hidden, 0, false)
JEXPOSE(int, heroMaxHealth, 100, jedv_t_hidden, 0, false)
JEXPOSE(JUUID, lastAttacker, "", jedv_t_hidden, 0, false)
JEXPOSE(bool, lastAttackerDied, false, jedv_t_hidden, 0, false)
JEXPOSE(bool, newAttacker, false, jedv_t_hidden, 0, false)
JEXPOSE(bool, lastAttackerHealthChanged, false, jedv_t_hidden, 0, false)
JEXPOSE(bool, gamepadStatusSet, false, jedv_t_hidden, 0, false)
JEXPOSE(int, lastAttackerHealth, 100, jedv_t_hidden, 0, false)
JEXPOSE(int, lastAttackerMaxHealth, 100, jedv_t_hidden, 0, false)
JEXPOSE(std::string, lastAttackerName, "", jedv_t_hidden, 0, false)
JEXPOSE(std::string, lastAttackerPicture, "", jedv_t_hidden, 0, false)
JEXPOSE(int, heroScore, 0, jedv_t_hidden, 0, false)
JEXPOSE_VECTOR_TRANSFORM(BrawlerRound, rounds, ToBrawlerRound, FromBrawlerRound, {}, jedv_t_vector, 0, false)
JEXPOSE_VECTOR_TRANSFORM(BrawlerDialog, dialogs, ToBrawlerDialog, FromBrawlerDialog, {}, jedv_t_vector, 0, false)
JEXPOSE(JUUID, music, "", jedv_t_so_soundeffect, 0, false)
JEXPOSE(JUUID, end_level_ready_music, "", jedv_t_so_soundeffect, 0, false)