JCLASS(Camera, GetCameras)
JTYPE(SceneObjectType, SO_Cameras)
JEXPOSE(std::string, uuid, "", jedv_t_hidden, 0, false)
JEXPOSE(bool, hidden, false, jedv_t_boolean, 1, false)
//JEXPOSE(std::string, name, ("cam." + std::to_string(GetCountFromCameras())), jedv_t_so_camera_name, 0, true)
JEXPOSE(std::string, name, "cam.", jedv_t_so_camera_name, 0, true)
JEXPOSE(bool, fitWindow, true, jedv_t_boolean, 1, true)
JEXPOSE_TRANSFORM(XMFLOAT3, position, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3, 0, false)
JEXPOSE_TRANSFORM_CALLBACK(XMFLOAT3, rotation, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3_angle, 0, false)
JEXPOSE(std::string, IBLIrradiance, "", jedv_t_te_texture, 1, false)
JEXPOSE(std::string, IBLPreFilteredEnvironment, "", jedv_t_te_texture, 1, false)
JEXPOSE(std::string, IBLBRDFLUT, "", jedv_t_te_texture, 1, false)
JEXPOSE(float, speed, 0.05f, jedv_t_float, 0, false)
JEXPOSE(float, white, 1.1f, jedv_t_float, 0, false)
JEXPOSE(float, minLogLuminance, -2.0f, jedv_t_float, 0, false)
JEXPOSE(float, maxLogLuminance, 10.0f, jedv_t_float, 0, false)
JEXPOSE(float, tau, 1.1f, jedv_t_float, 0, false)
JEXPOSE_ENUM(ProjectionsTypes, projectionType, PROJ_Perspective, jedv_t_enum, 1, true)
JEXPOSE_TRANSFORM(Perspective, perspective, ToPerspective, FromPerspective, Perspective(), jedv_t_object, 1, false)
JEXPOSE_TRANSFORM(Orthographic, orthographic, ToOrthographic, FromOrthographic, Orthographic(), jedv_t_object, 1, false)
JEXPOSE_VECTOR(std::string, renderPasses, {}, jedv_t_te_renderpass_vector, 1, false)
JEXPOSE(std::string, shadowMapLight, "", jedv_t_so_light, 1, false)
JEXPOSE(bool, mouseController, false, jedv_t_boolean, 1, false)
JEXPOSE(bool, useSwapChain, false, jedv_t_boolean, 1, false)
JEXPOSE_MAP_OBJECT(Controller, controllers, nlohmann::json::object({}), jedv_t_controller_vector, 1, false)
JPREVIEW(renderPassPreview, jedv_draw_renderpass_vector)
JTRACKUUID(Camera, Cameras, 0, true)
JTRACKUUID(Camera, WindowCameras, 0, fitWindow())
JTRACKUUID(Camera, SwapChainCameras, 1, ResolvesToSwapChain())
JTRACKUUID(Camera, MouseCameras, 1, mouseController())
