JCLASS(Renderable, GetRenderables)
JTYPE(SceneObjectType, SO_Renderables)
JEXPOSE(std::string, uuid, "", jedv_t_hidden, 0, false)
//JEXPOSE(std::string, name, ("renderable." + std::to_string(GetNumRenderables())), jedv_t_so_renderable_name, 0, true)
JEXPOSE(std::string, name, "renderable.1", jedv_t_so_renderable_name, 0, true)
JEXPOSE(bool, castShadows, true, jedv_t_boolean, 0, false)
JEXPOSE(bool, shadowed, true, jedv_t_boolean, 0, false)
JEXPOSE(bool, hidden, false, jedv_t_boolean, 0, false)
JEXPOSE(bool, ibl, false, jedv_t_boolean, 1, false)
JEXPOSE_TRANSFORM(MeshMaterial, meshMaterial, ToMeshMaterial, FromMeshMaterial, {}, jedv_t_mesh_material, 1, true)
JEXPOSE(std::string, model, "", jedv_t_te_model3d, 1, false)
JEXPOSE(std::string, animationSequence, "", jedv_t_animation_sequence, 1, false)
JEXPOSE(std::string, animation, "", jedv_t_animation, 1, false)
JEXPOSE(float, animationTime, 0.0f, jedv_t_hidden, 1, false)
JEXPOSE(float, animationTimeFactor, 1.0f, jedv_t_hidden, 1, false)
JEXPOSE(bool, animationPlay, false, jedv_t_hidden, 1, false)
JEXPOSE(bool, animationLoop, false, jedv_t_boolean, 1, false)
JEXPOSE(int, animationFrame, 0, jedv_t_hidden, 1, false)
JEXPOSE(bool, animationUseTransformation, false, jedv_t_boolean, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, position, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3, 1, false)
JEXPOSE_TRANSFORM_CALLBACK(XMFLOAT3, rotation, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3_angle, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, scale, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(1.0f, 1.0f, 1.0f), jedv_t_float3_f6, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, AABBCenter, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, AABBExtent, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(1.0f, 1.0f, 1.0f), jedv_t_float3_f6, 1, false)
JEXPOSE_SET(int, skipMeshes, {}, jedv_t_skip_meshes, 0, false)
JEXPOSE_ENUM(D3D_PRIMITIVE_TOPOLOGY, topology, D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST, jedv_t_enum, 1, false)
JEXPOSE(bool, uniqueMaterialInstance, false, jedv_t_boolean, 1, false)
JEXPOSE(bool, visible, true, jedv_t_boolean, 0, false)
JEXPOSE(bool, checkBoundingBox, true, jedv_t_boolean, 0, false)
JEXPOSE_TRANSFORM(DepthStencilDesc, depthStencil, ToDepthStencilDesc, FromDepthStencilDesc, DepthStencilDesc(), jedv_t_object, 1, false)
JEXPOSE_VECTOR(std::string, cameras, {}, jedv_t_so_camera_vector, 1, true)
JEXPOSE_VECTOR_TRANSFORM(PassMaterialOverride, passMaterialOverrides, ToPassMaterialOverride, FromPassMaterialOverride, {}, jedv_t_vector, 1, false)
JEXPOSE_VECTOR(std::string, renderNext, {}, jedv_t_so_renderable_vector, 1, false)
JEXPOSE(JUUID, attachedTo, "", jedv_t_so_renderable, 1, false)
JEXPOSE(JUUID, attachedBone, "", jedv_t_attachment_model3d_bone, 1, false)
JPREVIEW(shaderConstants, jedv_shader_constants_edit)
JEXPOSE_MAP_OBJECT(Controller, controllers, nlohmann::json::object({}), jedv_t_controller_vector, 1, false)
JEXPOSE_VECTOR_OBJECT(PhysicObject, physicObject, nlohmann::json::array({}), jedv_t_physic_object_vector, 1, false)
JTRACKUUID(Renderable, Renderables, 0, true)
JTRACKUUID(Renderable, Animables, 0, !animable.empty())
JTRACKUUID(Renderable, ShadowCasts, 0, castShadows())
