JCLASS(SoundFX, GetSoundEffects)
JTYPE(SceneObjectType, SO_SoundEffects)
JEXPOSE(std::string, uuid, "", jedv_t_string, 0, false)
//JEXPOSE(std::string, name, ("soundFX." + std::to_string(GetCountFromSoundEffects())), jedv_t_so_soundeffect_name, 0, true)
JEXPOSE(std::string, name, "soundFX.", jedv_t_so_soundeffect_name, 0, true)
JEXPOSE(std::string, sound, "", jedv_t_te_sound, 1, true)
JEXPOSE(float, volume, 1.0f, jedv_t_float, 1, false)
JEXPOSE(bool, autoPlay, false, jedv_t_boolean, 1, true)
JEXPOSE(bool, loop, false, jedv_t_boolean, 1, false)
JEXPOSE(bool, hidden, false, jedv_t_boolean, 0, false)
JEXPOSE(bool, destroyOnCompletion, true, jedv_t_boolean, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, position, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3, 0, false)
JEXPOSE_TRANSFORM(XMFLOAT3, rotation, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3_angle, 0, false)
JEXPOSE(unsigned int, instanceFlags, SoundEffectInstance_Default, jedv_t_sound_instance_flags, 1, true)
JTRACKUUID(SoundFX, SoundEffects, 0, true)
JTRACKUUID(SoundFX, Sound3DEffects, 0, !sound().empty() && nostd::bytesHas(instanceFlags(), SoundEffectInstance_Use3D))
