JCLASS(Light, GetLights)
JTYPE(SceneObjectType, SO_Lights)
JEXPOSE(std::string, uuid, "", jedv_t_hidden, 0, false)
JEXPOSE(bool, hidden, false, jedv_t_hidden, 0, false)
//JEXPOSE(std::string, name, ("light." + std::to_string(GetCountFromLights())), jedv_t_hidden, 0, true)
JEXPOSE(std::string, name, "light.", jedv_t_hidden, 0, true)
JEXPOSE_ENUM(LightType, lightType, LT_Ambient, jedv_t_lighttype, 1, true)
JEXPOSE_TRANSFORM(XMFLOAT3, position, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_hidden, 1, false)
JEXPOSE_TRANSFORM_CALLBACK(XMFLOAT3, rotation, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_hidden, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, color, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(1.0f, 1.0f, 1.0f), jedv_t_hidden, 1, true)
JEXPOSE(float, brightness, 1.0f, jedv_t_hidden, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, attenuation, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.01f, 0.02f), jedv_t_hidden, 1, false)
JEXPOSE(float, coneAngle, 45.0f, jedv_t_hidden, 1, false)
JEXPOSE(bool, hasShadowMaps, false, jedv_t_hidden, 1, true)
JEXPOSE(float, dirDist, 30.0f, jedv_t_hidden, 1, false)
JEXPOSE(unsigned int, shadowMapWidth, 1024, jedv_t_hidden, 1, false)
JEXPOSE(unsigned int, shadowMapHeight, 1024, jedv_t_hidden, 1, false)
JEXPOSE(float, viewWidth, 1024, jedv_t_hidden, 1, false)
JEXPOSE(float, viewRight, 0.0f, jedv_t_hidden, 1, false)
JEXPOSE(float, viewHeight, 1024, jedv_t_hidden, 1, false)
JEXPOSE(float, viewBottom, 0.0f, jedv_t_hidden, 1, false)
JEXPOSE(float, nearZ, 0.01f, jedv_t_hidden, 1, false)
JEXPOSE(float, farZ, 350.0f, jedv_t_hidden, 1, false)
JEXPOSE(float, zBias, 0.0001f, jedv_t_hidden, 1, false)
JEXPOSE_VECTOR(std::string, cameras, {}, jedv_t_so_camera_vector, 1, true)
JTRACKUUID(Light, Lights, 0, true)
JTRACKUUID(Light, ShadowMapLights, 0, hasShadowMaps())
