#if defined(JEXPOSE_TRACK_UUID_DECL)
#define JCLASS(CLASS,GETJOBJECTS)
#define JTYPE(TYPE,VALUE)
#define JEXPOSE(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_TRANSFORM(TYPE,ATT,TOTYPE,FROMTYPE,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_ENUM(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_VECTOR(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_VECTOR_TRANSFORM(TYPE,ATT,TOTYPE,FROMTYPE,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_SET(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_MAP_TRANSFORM(KEYTYPE,VALUETYPE,ATT,TOTYPE,FROMTYPE,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_MAP_OBJECT(TYPE, ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JPREVIEW(NAME,JEDVALUETYPE)
#define JTRACKUUID(CLASS,NAME,LIMIT,COND) \
	size_t GetCountFrom##NAME();\
	std::set<JUUID>& Get##NAME();\
	std::unique_ptr<CLASS>& GetFrom##NAME(JUUID uuid);\
	std::unique_ptr<CLASS>& GetFrom##NAME##ByName(std::string name);\
	std::vector<JNAME> GetNamesFrom##NAME();\
	std::vector<JUUIDName> GetUUIDNamesFrom##NAME();\
	JNAME GetNameFrom##NAME(JUUID uuid);\
	void Insert##CLASS##Into##NAME(JUUID uuid);\
	void Erase##CLASS##From##NAME(JUUID uuid);\

#endif

#if defined(JEXPOSE_TRACK_UUID_DEF)
#define JCLASS(CLASS,GETJOBJECTS)
#define JTYPE(TYPE,VALUE)
#define JEXPOSE(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_TRANSFORM(TYPE,ATT,TOTYPE,FROMTYPE,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_ENUM(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_VECTOR(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_VECTOR_TRANSFORM(TYPE,ATT,TOTYPE,FROMTYPE,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_SET(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_MAP_TRANSFORM(KEYTYPE,VALUETYPE,ATT,TOTYPE,FROMTYPE,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_MAP_OBJECT(TYPE, ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JPREVIEW(NAME,JEDVALUETYPE)
#define JTRACKUUID(CLASS,NAME,LIMIT,COND) \
	static std::set<JUUID> NAME;\
	size_t GetCountFrom##NAME() { return NAME.size(); }\
	std::set<JUUID>& Get##NAME() { return NAME; }\
	std::unique_ptr<CLASS>& GetFrom##NAME(JUUID uuid)\
	{\
		assert(NAME.contains(uuid));\
		return Get##CLASS##SceneObject(uuid);\
	}\
	std::unique_ptr<CLASS>& GetFrom##NAME##ByName(std::string name)\
	{\
		JUUID uuid = Get##CLASS##UUIDByName(name);\
		return GetFrom##NAME(uuid);\
	}\
	std::vector<JNAME> GetNamesFrom##NAME()\
	{\
		std::vector<JNAME> names;\
		std::transform(NAME.begin(), NAME.end(), std::back_inserter(names), [](JUUID uuid) { return Get##CLASS##Name(uuid); });\
		std::sort(names.begin(), names.end());\
		return names;\
	}\
	std::vector<JUUIDName> GetUUIDNamesFrom##NAME()\
	{\
		std::vector<JUUIDName> uuidNames;\
		std::transform(NAME.begin(), NAME.end(), std::back_inserter(uuidNames), [](JUUID uuid)\
			{\
				JUUIDName uuidName;\
				JUUID& uuid0 = std::get<0>(uuidName);\
				JUUID& name = std::get<1>(uuidName);\
				uuid0 = uuid;\
				name = Get##CLASS##Name(uuid);\
				return uuidName;\
			}\
		);\
		SortUUIDByName(uuidNames);\
		return uuidNames;\
	}\
	JNAME GetNameFrom##NAME(JUUID uuid)\
	{\
		assert(NAME.contains(uuid));\
		return Get##CLASS##Name(uuid);\
	}\
	void Insert##CLASS##Into##NAME(JUUID uuid)\
	{\
		if(LIMIT>0 && !NAME.contains(uuid))\
			assert(NAME.size()<LIMIT);\
		NAME.insert(uuid);\
	}\
	void Erase##CLASS##From##NAME(JUUID uuid)\
	{\
		NAME.erase(uuid);\
	}

#endif

#if defined(JEXPOSE_TRACK_UUID_INSERT)
#define JCLASS(CLASS,GETJOBJECTS)
#define JTYPE(TYPE,VALUE)
#define JEXPOSE(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_TRANSFORM(TYPE,ATT,TOTYPE,FROMTYPE,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_ENUM(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_VECTOR(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_VECTOR_TRANSFORM(TYPE,ATT,TOTYPE,FROMTYPE,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_SET(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_MAP_TRANSFORM(KEYTYPE,VALUETYPE,ATT,TOTYPE,FROMTYPE,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_MAP_OBJECT(TYPE, ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JPREVIEW(NAME,JEDVALUETYPE)
#define JTRACKUUID(CLASS,NAME,LIMIT,COND) if(COND) { Insert##CLASS##Into##NAME(uuid()); }

#endif

#if defined(JEXPOSE_TRACK_UUID_ERASE)
#define JCLASS(CLASS,GETJOBJECTS)
#define JTYPE(TYPE,VALUE)
#define JEXPOSE(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_TRANSFORM(TYPE,ATT,TOTYPE,FROMTYPE,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_ENUM(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_VECTOR(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_VECTOR_TRANSFORM(TYPE,ATT,TOTYPE,FROMTYPE,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_SET(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_MAP_TRANSFORM(KEYTYPE,VALUETYPE,ATT,TOTYPE,FROMTYPE,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_MAP_OBJECT(TYPE, ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JPREVIEW(NAME,JEDVALUETYPE)
#define JTRACKUUID(CLASS,NAME,LIMIT,COND) Erase##CLASS##From##NAME(uuid());

#endif

#if defined(JEXPOSE_TRACK_UUID_CLEAR)
#define JCLASS(CLASS,GETJOBJECTS)
#define JTYPE(TYPE,VALUE)
#define JEXPOSE(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_TRANSFORM(TYPE,ATT,TOTYPE,FROMTYPE,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_ENUM(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_VECTOR(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_VECTOR_TRANSFORM(TYPE,ATT,TOTYPE,FROMTYPE,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_SET(TYPE,ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_MAP_TRANSFORM(KEYTYPE,VALUETYPE,ATT,TOTYPE,FROMTYPE,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JEXPOSE_MAP_OBJECT(TYPE, ATT,INITIAL,JEDVALUETYPE,UPDATEMASK,REQUIREDTOCREATE)
#define JPREVIEW(NAME,JEDVALUETYPE)
#define JTRACKUUID(CLASS,NAME,LIMIT,COND) NAME.clear();

#endif
