JCLASS(Thug, _)
JEXPOSE(float, combatMinDistanceToAttack, 0.01f, jedv_t_float, 1, false)
JEXPOSE(bool, combatEnabled, false, jedv_t_boolean, 1, false)
JEXPOSE(float, idleTimeFactor, 1.0f, jedv_t_float, 1, false)
JEXPOSE(std::string, idleAnimation, "", jedv_t_controller_animation_sequence, 1, false)
JEXPOSE(float, combatIdleTimeFactor, 1.0f, jedv_t_float, 1, false)
JEXPOSE(std::string, combatIdleAnimation, "", jedv_t_controller_animation_sequence, 1, false)
JEXPOSE(float, walkSpeed, 3.0f, jedv_t_float, 1, false)
JEXPOSE(float, combatMoveFwTimeFactor, 1.0f, jedv_t_float, 1, false)
JEXPOSE(std::string, combatMoveFwAnimation, "", jedv_t_controller_animation_sequence, 1, false)
JEXPOSE(float, combatMoveNearFarAngle, 70.0f, jedv_t_float, 1, false)
JEXPOSE(float, combatMoveNearFarTimeFactor, 1.0f, jedv_t_float, 1, false)
JEXPOSE(float, combatMoveFarSpeed, 3.0f, jedv_t_float, 1, false)
JEXPOSE(std::string, combatMoveFarAnimation, "", jedv_t_controller_animation_sequence, 1, false)
JEXPOSE(float, combatMoveNearSpeed, 3.0f, jedv_t_float, 1, false)
JEXPOSE(std::string, combatMoveNearAnimation, "", jedv_t_controller_animation_sequence, 1, false)
JEXPOSE(float, combatPunchTimeFactor, 1.0f, jedv_t_float, 1, false)
JEXPOSE(std::string, combatPunchAnimation, "", jedv_t_controller_animation_sequence, 1, false)
JEXPOSE(float, deathTimeFactor, 1.0f, jedv_t_float, 1, false)
JEXPOSE(std::string, deathAnimation, "", jedv_t_controller_animation_sequence, 1, false)
JEXPOSE(int, damage, 10, jedv_t_integer, 1, false)
JEXPOSE_VECTOR(JUUID, punchSounds, {}, jedv_t_so_soundeffect_vector, 1, false)
JEXPOSE_VECTOR(JUUID, deathSounds, {}, jedv_t_so_soundeffect_vector, 1, false)
JEXPOSE(unsigned int, score, 1000, jedv_t_unsigned, 1, false)
JEXPOSE(bool, canBeBlocked, true, jedv_t_boolean, 1, false)
JEXPOSE(float, blockPercentage, 1.0f, jedv_t_float, 1, false)