JCLASS(Thug, _)
JEXPOSE_TRANSFORM(ControllerBinding, sceneController, ToControllerBinding, FromControllerBinding, {}, jedv_t_so_controller_instance, 1, false)
JEXPOSE(float, walkSpeed, 3.0f, jedv_t_float, 1, false)
JEXPOSE(float, combatMinDistanceToAttack, 0.01f, jedv_t_float, 1, false)
JEXPOSE(float, combatIdleTimeFactor, 1.0f, jedv_t_float, 1, false)
JEXPOSE(float, combatMoveFwTimeFactor, 1.0f, jedv_t_float, 1, false)
JEXPOSE(float, combatMoveNearFarAngle, 70.0f, jedv_t_float, 1, false)
JEXPOSE(float, combatMoveNearFarTimeFactor, 1.0f, jedv_t_float, 1, false)
JEXPOSE(float, combatPunchTimeFactor, 1.0f, jedv_t_float, 1, false)
JEXPOSE(int, damage, 10, jedv_t_integer, 1, false)
JEXPOSE(int, health, 100, jedv_t_integer, 1, false)
JEXPOSE_VECTOR(JUUID, punchSounds, {}, jedv_t_so_soundeffect_vector, 1, false)
JEXPOSE_VECTOR(JUUID, deathSounds, {}, jedv_t_so_soundeffect_vector, 1, false)
JEXPOSE(unsigned int, score, 1000, jedv_t_unsigned, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, lookToSwapVector, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(1.0f, 1.0f, 1.0f), jedv_t_float3, 1, false)
