JCLASS(Thug, _)
JEXPOSE(std::string, idleAnimation, "", jedv_t_string, 1, false)
JEXPOSE(std::string, combatIdleAnimation, "", jedv_t_string, 1, false)
JEXPOSE(std::string, combatMoveFwAnimation, "", jedv_t_string, 1, false)
JEXPOSE(std::string, combatMoveFarAnimation, "", jedv_t_string, 1, false)
JEXPOSE(std::string, combatMoveNearAnimation, "", jedv_t_string, 1, false)
JEXPOSE(std::string, combatPunchAnimation, "", jedv_t_string, 1, false)
JEXPOSE(std::string, deathAnimation, "", jedv_t_string, 1, false)
JEXPOSE(float, walkSpeed, 3.0f, jedv_t_float, 1, false)
JEXPOSE(float, combatMinDistanceToAttack, 0.01f, jedv_t_float, 1, false)
JEXPOSE(float, combatIdleTimeFactor, 1.0f, jedv_t_float, 1, false)
JEXPOSE(float, combatMoveFwTimeFactor, 1.0f, jedv_t_float, 1, false)
JEXPOSE(float, combatMoveNearFarAngle, 70.0f, jedv_t_float, 1, false)
JEXPOSE(float, combatMoveNearFarTimeFactor, 1.0f, jedv_t_float, 1, false)
JEXPOSE(float, combatPunchTimeFactor, 1.0f, jedv_t_float, 1, false)
JEXPOSE(int, damage, 10, jedv_t_integer, 1, false)
JEXPOSE(int, health, 100, jedv_t_integer, 1, false)
JEXPOSE_VECTOR(JUUID, punchSounds, {}, jedv_t_so_soundeffect_vector, 1, false)
JEXPOSE_VECTOR(JUUID, deathSounds, {}, jedv_t_so_soundeffect_vector, 1, false)
JEXPOSE(unsigned int, score, 1000, jedv_t_unsigned, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, lookToSwapVector, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(1.0f, 1.0f, 1.0f), jedv_t_float3, 1, false)
