JCLASS(Venom, _)
JEXPOSE_TRANSFORM(ControllerBinding, sceneController, ToControllerBinding, FromControllerBinding, {}, jedv_t_so_controller_instance, 1, false)
JEXPOSE(float, lookToThreshold, 0.03f, jedv_t_float, 1, false)
JEXPOSE(float, walkThreshold, 0.05f, jedv_t_float, 1, false)
JEXPOSE(float, runThreshold, 0.4f, jedv_t_float, 1, false)
JEXPOSE(float, walkSpeed, 3.0f, jedv_t_float, 1, false)
JEXPOSE(float, runSpeed, 10.0f, jedv_t_float, 1, false)
JEXPOSE(float, runningJumpTime, 0.375f, jedv_t_float, 1, false)
JEXPOSE(float, jumpDashTime, 0.275f, jedv_t_float, 1, false)
JEXPOSE(float, fixedDownDisplacement, -0.1f, jedv_t_float, 1, false)
JEXPOSE(float, jumpSpeed, 1.0f, jedv_t_float, 1, false)
JEXPOSE(bool, canAttachToWall, false, jedv_t_boolean, 1, false)
JEXPOSE(float, wallMoveThreshold, 0.05f, jedv_t_float, 1, false)
JEXPOSE(float, wallMoveSpeed, 3.0f, jedv_t_float, 1, false)
JEXPOSE(float, wallMoveMinTimeFactor, 0.3f, jedv_t_float, 1, false)
JEXPOSE(float, wallMoveMaxTimeFactor, 1.3f, jedv_t_float, 1, false)
JEXPOSE(int, health, 100, jedv_t_integer, 1, false)
JEXPOSE(int, damage, 10, jedv_t_integer, 1, false)
JEXPOSE_VECTOR(JUUID, punchSounds, {}, jedv_t_so_soundeffect_vector, 1, false)
JEXPOSE_VECTOR(JUUID, punchDeathSound, {}, jedv_t_so_soundeffect_vector, 1, false)
JEXPOSE_FLAG(blockedWallMovementMask, 0U, GetBlockedWallMovementMasks, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, swingWebMaxScale, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(1.0f, 1.0f, 1.0f), jedv_t_float3, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, swingWebMaxTime, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(1.0f, 1.0f, 1.0f), jedv_t_float3, 1, false)
JEXPOSE(JUUID, webModel, "", jedv_t_te_model3d, 1, false)
