JCLASS(VenomController, _)
JEXPOSE(float, lookToThreshold, 0.03f, jedv_t_float, 1, false)
JEXPOSE(float, walkThreshold, 0.05f, jedv_t_float, 1, false)
JEXPOSE(float, runThreshold, 0.4f, jedv_t_float, 1, false)
JEXPOSE(float, walkSpeed, 3.0f, jedv_t_float, 1, false)
JEXPOSE(float, runSpeed, 10.0f, jedv_t_float, 1, false)
JEXPOSE(float, jumpHeight, 3.5f, jedv_t_float, 1, false)
JEXPOSE(int, jumpTime, 375, jedv_t_integer, 1, false)
JEXPOSE(int, runningJumpTime, 375, jedv_t_integer, 1, false)
JEXPOSE(int, runningJumpAttackTime, 275, jedv_t_integer, 1, false)
