JCLASS(Material, _)
JTYPE(TemplateType, T_Materials)
JEXPOSE(std::string, uuid, "", jedv_t_hidden, 0, false)
JEXPOSE(std::string, name, "", jedv_t_te_material_name, 0, true)
JEXPOSE(std::string, shader_vs, "", jedv_t_te_shader, 1, true)
JEXPOSE(std::string, shader_ps, "", jedv_t_te_shader, 1, true)
JEXPOSE_VECTOR_TRANSFORM(MaterialSamplerDesc, samplers, ToMaterialSamplerDesc, FromMaterialSamplerDesc, {}, jedv_t_vector, 1, false)
JEXPOSE_VECTOR_TRANSFORM(MaterialInitialValuePair, mappedValues, ToMaterialInitialValuePair, FromMaterialInitialValuePair, {}, jedv_t_vector, 1, false)
JEXPOSE_MAP_TRANSFORM(TextureShaderUsage, std::string, textures, ToTextureShaderUsagePair, FromTextureShaderUsagePair, {}, jedv_t_map, 1, false)
JEXPOSE_TRANSFORM(RasterizerDesc, rasterizerState, ToRasterizerDesc, FromRasterizerDesc, RasterizerDesc(), jedv_t_object, 1, false)
JEXPOSE_TRANSFORM(BlendDesc, blendState, ToBlendDesc, FromBlendDesc, BlendDesc(), jedv_t_object, 1, false)
JEXPOSE(bool, overrideDepthStencil, false, jedv_t_boolean, 0, false)
JEXPOSE_TRANSFORM(DepthStencilDesc, depthStencil, ToDepthStencilDesc, FromDepthStencilDesc, DepthStencilDesc(), jedv_t_object, 1, false)
