JCLASS(PhysicGeometry, _)
JTYPE(TemplateType, T_PhysicGeometries)
JEXPOSE(std::string, uuid, "", jedv_t_hidden, 0, false)
JEXPOSE(std::string, name, "", jedv_t_te_model3d_name, 0, true)
JEXPOSE(std::string, path, "", jedv_t_model3d_filepath, 1, true)
