JCLASS(Texture, _)
JTYPE(TemplateType, T_Textures)
JEXPOSE(std::string, uuid, "", jedv_t_hidden, 0, false)
JEXPOSE(std::string, name, "", jedv_t_te_texture_name, 0, true)
JEXPOSE_ENUM(DXGI_FORMAT, format, DXGI_FORMAT_R8G8B8A8_UNORM_SRGB, jedv_t_hidden, 1, false)
JEXPOSE(unsigned int, width, 128, jedv_t_hidden, 1, false)
JEXPOSE(unsigned int, height, 128, jedv_t_hidden, 1, false)
JEXPOSE(unsigned int, mipLevels, 0, jedv_t_hidden, 1, false)
JEXPOSE(unsigned int, numFrames, 0, jedv_t_hidden, 1, false)
JEXPOSE_ENUM(TextureType, type, TextureType_2D, jedv_t_hidden, 1, true)
JEXPOSE_VECTOR(std::string, images, {}, jedv_t_filepath_vector_image, 1, true)
