JCLASS(Shader, _)
JTYPE(TemplateType, T_Shaders)
JEXPOSE(std::string, uuid, "", jedv_t_hidden, 0, false)
JEXPOSE(std::string, name, "", jedv_t_te_shader_name, 0, true)
JEXPOSE(std::string, path, "", jedv_t_shaders_filepath, 1, true)
