JCLASS(GreenGoblin, _)
JEXPOSE_TRANSFORM(XMFLOAT3, leftSpot, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, rightSpot, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3, 1, false)
JEXPOSE(float, timeBetweenGlides, 0.0f, jedv_t_float, 1, false)
JEXPOSE(float, glideSpeed, 2.0f, jedv_t_float, 1, false)
JEXPOSE(std::string, glideIdleAnimation, "", jedv_t_controller_animation_sequence, 1, false)
JEXPOSE(std::string, glideThrowAnimation, "", jedv_t_controller_animation_sequence, 1, false)
JEXPOSE(std::string, glideThrowBone, "", jedv_t_controller_model3d_bone, 1, false)
JEXPOSE(float, bombMaxHeight, 1.0f, jedv_t_float, 1, false)
JEXPOSE(float, glideMinDistancetoAttack, 1.0f, jedv_t_float, 1, false)
JEXPOSE(JUUID, bomb, "", jedv_t_te_mold, 1, false)
JEXPOSE(JUUID, glider, "", jedv_t_so_renderable, 1, false)
JEXPOSE(JUUID, handbomb, "", jedv_t_so_renderable, 1, false)
JEXPOSE(float, stopGlideHeight, -0.07f, jedv_t_float, 1, false)
