JCLASS(PhysicObject, _)
JEXPOSE_ENUM(PhysicsBehavior, behavior, PB_Static, jedv_t_physic_behavior, 1, false)
JEXPOSE(std::string, geometry, "", jedv_t_te_physycgeometry, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT4, color, ToXMFLOAT4, FromXMFLOAT4, XMFLOAT4(0.2f, 1.0f, 0.78f, 0.5f), jedv_t_color_float4, 1, false)
JEXPOSE(bool, overrideColor, false, jedv_t_boolean, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, localPosition, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, localRotation, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3_angle, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, localScale, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(1.0f, 1.0f, 1.0f), jedv_t_float3, 1, false)
JEXPOSE(float, staticFriction, 0.5f, jedv_t_float, 1, false)
JEXPOSE(float, dynamicFriction, 0.5f, jedv_t_float, 1, false)
JEXPOSE(float, restitution, 0.1f, jedv_t_float, 1, false)
JEXPOSE(float, density, 1.0f, jedv_t_float, 1, false)
JEXPOSE(bool, updateFromCharacterPosition, true, jedv_t_boolean, 1, false)
JEXPOSE(bool, useFootPosition, false, jedv_t_boolean, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, linearVelocity, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, angularVelocity, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3, 1, false)
