JCLASS(PhysicObject, _)
JEXPOSE_ENUM(PhysicsBehavior, behavior, PB_Static, jedv_t_physic_behavior, 1, false)
JEXPOSE(float, staticFriction, 0.5f, jedv_t_float, 1, false)
JEXPOSE(float, dynamicFriction, 0.5f, jedv_t_float, 1, false)
JEXPOSE(float, restitution, 0.1f, jedv_t_float, 1, false)
JEXPOSE(float, density, 1.0f, jedv_t_float, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, linearVelocity, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3, 0, false)
JEXPOSE_TRANSFORM(XMFLOAT3, angularVelocity, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3_angle, 0, false)
