JCLASS(PhysicObject, _)
JEXPOSE_ENUM(PhysicsBehavior, behavior, PB_Static, jedv_t_physic_behavior, 1, false)
JEXPOSE(float, mass, 1.0f, jedv_t_float, 1, false)
JEXPOSE_TRANSFORM(XMFLOAT3, linearVelocity, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3, 0, false)
JEXPOSE_TRANSFORM(XMFLOAT3, angularVelocity, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3_angle, 0, false)
JEXPOSE_TRANSFORM(XMFLOAT3, linearAcceleration, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3, 0, false)
JEXPOSE_TRANSFORM(XMFLOAT3, angularAcceleration, ToXMFLOAT3, FromXMFLOAT3, XMFLOAT3(0.0f, 0.0f, 0.0f), jedv_t_float3_angle, 0, false)