#ifdef JEXPOSE_CREATOR_JSON_DECL
#undef JEXPOSE_CREATOR_JSON_DECL
#endif

#ifdef JEXPOSE_CREATOR_JSON_DEF
#undef JEXPOSE_CREATOR_JSON_DEF
return created; }
#endif

#ifdef JEXPOSE_ATT_DECL
#undef JEXPOSE_ATT_DECL
#endif

#ifdef JEXPOSE_ATT_INIT
#undef JEXPOSE_ATT_INIT
#endif

#ifdef JEXPOSE_ATT_ORDER
#undef JEXPOSE_ATT_ORDER
}); }
#endif

#ifdef JEXPOSE_ATT_FLAGS
#undef JEXPOSE_ATT_FLAGS
};
#endif

#ifdef JEXPOSE_ATT_UPDATE
#undef JEXPOSE_ATT_UPDATE
};
#endif

#ifdef JEXPOSE_ATT_DESTROY
#undef JEXPOSE_ATT_DESTROY
#endif

#ifdef JEXPOSE_EDITOR_DRAWERS_DECL
#undef JEXPOSE_EDITOR_DRAWERS_DECL
#endif

#ifdef JEXPOSE_EDITOR_DRAWERS_DEF
}); }
#undef JEXPOSE_EDITOR_DRAWERS_DEF
#endif

#ifdef JEXPOSE_EDITOR_SAVE_FILE
json.push_back(obj); });
#undef JEXPOSE_EDITOR_SAVE_FILE
#endif

#ifdef JEXPOSE_EDITOR_WRITE_JSON
#undef JEXPOSE_EDITOR_WRITE_JSON
#endif

#ifdef JEXPOSE_EDITOR_PREVIEW_DECL
#undef JEXPOSE_EDITOR_PREVIEW_DECL
#endif

#ifdef JEXPOSE_EDITOR_PREVIEW_DEF
}); }
#undef JEXPOSE_EDITOR_PREVIEW_DEF
#endif

#ifdef JEXPOSE_TRACK_UUID_DECL
#undef JEXPOSE_TRACK_UUID_DECL
#endif

#ifdef JEXPOSE_TRACK_UUID_DEF
#undef JEXPOSE_TRACK_UUID_DEF
#endif

#ifdef JEXPOSE_TRACK_UUID_INSERT
#undef JEXPOSE_TRACK_UUID_INSERT
#endif

#ifdef JEXPOSE_TRACK_UUID_ERASE
#undef JEXPOSE_TRACK_UUID_ERASE
#endif

#ifdef JEXPOSE_TRACK_UUID_CLEAR
#undef JEXPOSE_TRACK_UUID_CLEAR
#endif

#ifdef JEXPOSE_CREATOR_REQUIRED
#undef JEXPOSE_CREATOR_REQUIRED
return requiredAtts; }
#endif

#ifdef JEXPOSE_CREATOR_DRAWERS_DECL
#undef JEXPOSE_CREATOR_DRAWERS_DECL
#endif

#ifdef JEXPOSE_CREATOR_DRAWERS_DEF
return creatorDrawers; }
#undef JEXPOSE_CREATOR_DRAWERS_DEF
#endif

#ifdef JEXPOSE_CREATOR_VALIDATOR_DECL
#undef JEXPOSE_CREATOR_VALIDATOR_DECL
#endif

#ifdef JEXPOSE_CREATOR_VALIDATOR_DEF
return creatorValidator; }
#undef JEXPOSE_CREATOR_VALIDATOR_DEF
#endif

#undef JCLASS
#undef JTYPE
#undef JEXPOSE
#undef JEXPOSE_CALLBACK
#undef JEXPOSE_TRANSFORM
#undef JEXPOSE_ENUM
#undef JEXPOSE_VECTOR
#undef JEXPOSE_VECTOR_TRANSFORM
#undef JEXPOSE_SET
#undef JEXPOSE_MAP_TRANSFORM
#undef JEXPOSE_MAP_OBJECT
#undef JEXPOSE_VECTOR_OBJECT
#undef JPREVIEW
#undef JTRACKUUID
